// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.20.3
// source: api/videoCore/service/v1/comment.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Comment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                        // 评论id
	VideoId       string                 `protobuf:"bytes,2,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`               // 视频id
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`                              // 评论内容
	Date          string                 `protobuf:"bytes,4,opt,name=date,proto3" json:"date,omitempty"`                                    // 评论日期
	LikeCount     int64                  `protobuf:"varint,5,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"`        // 点赞数
	ReplyCount    int64                  `protobuf:"varint,6,opt,name=reply_count,json=replyCount,proto3" json:"reply_count,omitempty"`     // 回复数
	UserId        string                 `protobuf:"bytes,7,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                  // 用户id
	ParentId      string                 `protobuf:"bytes,8,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`            // 父评论id
	ReplyUserId   string                 `protobuf:"bytes,9,opt,name=reply_user_id,json=replyUserId,proto3" json:"reply_user_id,omitempty"` // 回复用户id
	Comments      []*Comment             `protobuf:"bytes,10,rep,name=comments,proto3" json:"comments,omitempty"`                           // 子评论
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Comment) Reset() {
	*x = Comment{}
	mi := &file_api_videoCore_service_v1_comment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Comment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Comment) ProtoMessage() {}

func (x *Comment) ProtoReflect() protoreflect.Message {
	mi := &file_api_videoCore_service_v1_comment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Comment.ProtoReflect.Descriptor instead.
func (*Comment) Descriptor() ([]byte, []int) {
	return file_api_videoCore_service_v1_comment_proto_rawDescGZIP(), []int{0}
}

func (x *Comment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Comment) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

func (x *Comment) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Comment) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *Comment) GetLikeCount() int64 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

func (x *Comment) GetReplyCount() int64 {
	if x != nil {
		return x.ReplyCount
	}
	return 0
}

func (x *Comment) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Comment) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *Comment) GetReplyUserId() string {
	if x != nil {
		return x.ReplyUserId
	}
	return ""
}

func (x *Comment) GetComments() []*Comment {
	if x != nil {
		return x.Comments
	}
	return nil
}

type CreateCommentReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       string                 `protobuf:"bytes,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`               // 视频id
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                  // 用户id
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`                              // 评论内容
	ParentId      string                 `protobuf:"bytes,4,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`            // 父评论id
	ReplyUserId   string                 `protobuf:"bytes,5,opt,name=reply_user_id,json=replyUserId,proto3" json:"reply_user_id,omitempty"` // 回复用户id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCommentReq) Reset() {
	*x = CreateCommentReq{}
	mi := &file_api_videoCore_service_v1_comment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCommentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCommentReq) ProtoMessage() {}

func (x *CreateCommentReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_videoCore_service_v1_comment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCommentReq.ProtoReflect.Descriptor instead.
func (*CreateCommentReq) Descriptor() ([]byte, []int) {
	return file_api_videoCore_service_v1_comment_proto_rawDescGZIP(), []int{1}
}

func (x *CreateCommentReq) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

func (x *CreateCommentReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateCommentReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreateCommentReq) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *CreateCommentReq) GetReplyUserId() string {
	if x != nil {
		return x.ReplyUserId
	}
	return ""
}

type CreateCommentResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *Metadata              `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Comment       *Comment               `protobuf:"bytes,2,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCommentResp) Reset() {
	*x = CreateCommentResp{}
	mi := &file_api_videoCore_service_v1_comment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCommentResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCommentResp) ProtoMessage() {}

func (x *CreateCommentResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_videoCore_service_v1_comment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCommentResp.ProtoReflect.Descriptor instead.
func (*CreateCommentResp) Descriptor() ([]byte, []int) {
	return file_api_videoCore_service_v1_comment_proto_rawDescGZIP(), []int{2}
}

func (x *CreateCommentResp) GetMeta() *Metadata {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *CreateCommentResp) GetComment() *Comment {
	if x != nil {
		return x.Comment
	}
	return nil
}

type RemoveCommentReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommentId     string                 `protobuf:"bytes,1,opt,name=comment_id,json=commentId,proto3" json:"comment_id,omitempty"` // 评论id
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`          // 用户id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveCommentReq) Reset() {
	*x = RemoveCommentReq{}
	mi := &file_api_videoCore_service_v1_comment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveCommentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveCommentReq) ProtoMessage() {}

func (x *RemoveCommentReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_videoCore_service_v1_comment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveCommentReq.ProtoReflect.Descriptor instead.
func (*RemoveCommentReq) Descriptor() ([]byte, []int) {
	return file_api_videoCore_service_v1_comment_proto_rawDescGZIP(), []int{3}
}

func (x *RemoveCommentReq) GetCommentId() string {
	if x != nil {
		return x.CommentId
	}
	return ""
}

func (x *RemoveCommentReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type RemoveCommentResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *Metadata              `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveCommentResp) Reset() {
	*x = RemoveCommentResp{}
	mi := &file_api_videoCore_service_v1_comment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveCommentResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveCommentResp) ProtoMessage() {}

func (x *RemoveCommentResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_videoCore_service_v1_comment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveCommentResp.ProtoReflect.Descriptor instead.
func (*RemoveCommentResp) Descriptor() ([]byte, []int) {
	return file_api_videoCore_service_v1_comment_proto_rawDescGZIP(), []int{4}
}

func (x *RemoveCommentResp) GetMeta() *Metadata {
	if x != nil {
		return x.Meta
	}
	return nil
}

type ListComment4VideoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       string                 `protobuf:"bytes,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"` // 视频id
	PageStats     *PageStatsReq          `protobuf:"bytes,2,opt,name=page_stats,json=pageStats,proto3" json:"page_stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListComment4VideoReq) Reset() {
	*x = ListComment4VideoReq{}
	mi := &file_api_videoCore_service_v1_comment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListComment4VideoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListComment4VideoReq) ProtoMessage() {}

func (x *ListComment4VideoReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_videoCore_service_v1_comment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListComment4VideoReq.ProtoReflect.Descriptor instead.
func (*ListComment4VideoReq) Descriptor() ([]byte, []int) {
	return file_api_videoCore_service_v1_comment_proto_rawDescGZIP(), []int{5}
}

func (x *ListComment4VideoReq) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

func (x *ListComment4VideoReq) GetPageStats() *PageStatsReq {
	if x != nil {
		return x.PageStats
	}
	return nil
}

type ListComment4VideoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *Metadata              `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	CommentList   []*Comment             `protobuf:"bytes,2,rep,name=comment_list,json=commentList,proto3" json:"comment_list,omitempty"`
	PageStats     *PageStatsResp         `protobuf:"bytes,3,opt,name=page_stats,json=pageStats,proto3" json:"page_stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListComment4VideoResp) Reset() {
	*x = ListComment4VideoResp{}
	mi := &file_api_videoCore_service_v1_comment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListComment4VideoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListComment4VideoResp) ProtoMessage() {}

func (x *ListComment4VideoResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_videoCore_service_v1_comment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListComment4VideoResp.ProtoReflect.Descriptor instead.
func (*ListComment4VideoResp) Descriptor() ([]byte, []int) {
	return file_api_videoCore_service_v1_comment_proto_rawDescGZIP(), []int{6}
}

func (x *ListComment4VideoResp) GetMeta() *Metadata {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *ListComment4VideoResp) GetCommentList() []*Comment {
	if x != nil {
		return x.CommentList
	}
	return nil
}

func (x *ListComment4VideoResp) GetPageStats() *PageStatsResp {
	if x != nil {
		return x.PageStats
	}
	return nil
}

type ListChildComment4CommentReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommentId     string                 `protobuf:"bytes,1,opt,name=comment_id,json=commentId,proto3" json:"comment_id,omitempty"`
	PageStats     *PageStatsReq          `protobuf:"bytes,2,opt,name=page_stats,json=pageStats,proto3" json:"page_stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChildComment4CommentReq) Reset() {
	*x = ListChildComment4CommentReq{}
	mi := &file_api_videoCore_service_v1_comment_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChildComment4CommentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChildComment4CommentReq) ProtoMessage() {}

func (x *ListChildComment4CommentReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_videoCore_service_v1_comment_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChildComment4CommentReq.ProtoReflect.Descriptor instead.
func (*ListChildComment4CommentReq) Descriptor() ([]byte, []int) {
	return file_api_videoCore_service_v1_comment_proto_rawDescGZIP(), []int{7}
}

func (x *ListChildComment4CommentReq) GetCommentId() string {
	if x != nil {
		return x.CommentId
	}
	return ""
}

func (x *ListChildComment4CommentReq) GetPageStats() *PageStatsReq {
	if x != nil {
		return x.PageStats
	}
	return nil
}

type ListChildComment4CommentResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *Metadata              `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	CommentList   []*Comment             `protobuf:"bytes,2,rep,name=comment_list,json=commentList,proto3" json:"comment_list,omitempty"`
	PageStats     *PageStatsResp         `protobuf:"bytes,3,opt,name=page_stats,json=pageStats,proto3" json:"page_stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChildComment4CommentResp) Reset() {
	*x = ListChildComment4CommentResp{}
	mi := &file_api_videoCore_service_v1_comment_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChildComment4CommentResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChildComment4CommentResp) ProtoMessage() {}

func (x *ListChildComment4CommentResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_videoCore_service_v1_comment_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChildComment4CommentResp.ProtoReflect.Descriptor instead.
func (*ListChildComment4CommentResp) Descriptor() ([]byte, []int) {
	return file_api_videoCore_service_v1_comment_proto_rawDescGZIP(), []int{8}
}

func (x *ListChildComment4CommentResp) GetMeta() *Metadata {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *ListChildComment4CommentResp) GetCommentList() []*Comment {
	if x != nil {
		return x.CommentList
	}
	return nil
}

func (x *ListChildComment4CommentResp) GetPageStats() *PageStatsResp {
	if x != nil {
		return x.PageStats
	}
	return nil
}

type GetCommentByIdReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommentId     string                 `protobuf:"bytes,1,opt,name=comment_id,json=commentId,proto3" json:"comment_id,omitempty"` // 评论id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommentByIdReq) Reset() {
	*x = GetCommentByIdReq{}
	mi := &file_api_videoCore_service_v1_comment_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommentByIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommentByIdReq) ProtoMessage() {}

func (x *GetCommentByIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_videoCore_service_v1_comment_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommentByIdReq.ProtoReflect.Descriptor instead.
func (*GetCommentByIdReq) Descriptor() ([]byte, []int) {
	return file_api_videoCore_service_v1_comment_proto_rawDescGZIP(), []int{9}
}

func (x *GetCommentByIdReq) GetCommentId() string {
	if x != nil {
		return x.CommentId
	}
	return ""
}

type GetCommentByIdResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *Metadata              `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Comment       *Comment               `protobuf:"bytes,2,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommentByIdResp) Reset() {
	*x = GetCommentByIdResp{}
	mi := &file_api_videoCore_service_v1_comment_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommentByIdResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommentByIdResp) ProtoMessage() {}

func (x *GetCommentByIdResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_videoCore_service_v1_comment_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommentByIdResp.ProtoReflect.Descriptor instead.
func (*GetCommentByIdResp) Descriptor() ([]byte, []int) {
	return file_api_videoCore_service_v1_comment_proto_rawDescGZIP(), []int{10}
}

func (x *GetCommentByIdResp) GetMeta() *Metadata {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *GetCommentByIdResp) GetComment() *Comment {
	if x != nil {
		return x.Comment
	}
	return nil
}

type CountResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Count         int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountResult) Reset() {
	*x = CountResult{}
	mi := &file_api_videoCore_service_v1_comment_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountResult) ProtoMessage() {}

func (x *CountResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_videoCore_service_v1_comment_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountResult.ProtoReflect.Descriptor instead.
func (*CountResult) Descriptor() ([]byte, []int) {
	return file_api_videoCore_service_v1_comment_proto_rawDescGZIP(), []int{11}
}

func (x *CountResult) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CountResult) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type CountComment4VideoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       []string               `protobuf:"bytes,1,rep,name=video_id,json=videoId,proto3" json:"video_id,omitempty"` // 视频id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountComment4VideoReq) Reset() {
	*x = CountComment4VideoReq{}
	mi := &file_api_videoCore_service_v1_comment_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountComment4VideoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountComment4VideoReq) ProtoMessage() {}

func (x *CountComment4VideoReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_videoCore_service_v1_comment_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountComment4VideoReq.ProtoReflect.Descriptor instead.
func (*CountComment4VideoReq) Descriptor() ([]byte, []int) {
	return file_api_videoCore_service_v1_comment_proto_rawDescGZIP(), []int{12}
}

func (x *CountComment4VideoReq) GetVideoId() []string {
	if x != nil {
		return x.VideoId
	}
	return nil
}

type CountComment4VideoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *Metadata              `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Results       []*CountResult         `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountComment4VideoResp) Reset() {
	*x = CountComment4VideoResp{}
	mi := &file_api_videoCore_service_v1_comment_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountComment4VideoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountComment4VideoResp) ProtoMessage() {}

func (x *CountComment4VideoResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_videoCore_service_v1_comment_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountComment4VideoResp.ProtoReflect.Descriptor instead.
func (*CountComment4VideoResp) Descriptor() ([]byte, []int) {
	return file_api_videoCore_service_v1_comment_proto_rawDescGZIP(), []int{13}
}

func (x *CountComment4VideoResp) GetMeta() *Metadata {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *CountComment4VideoResp) GetResults() []*CountResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type CountComment4UserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        []string               `protobuf:"bytes,1,rep,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 用户id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountComment4UserReq) Reset() {
	*x = CountComment4UserReq{}
	mi := &file_api_videoCore_service_v1_comment_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountComment4UserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountComment4UserReq) ProtoMessage() {}

func (x *CountComment4UserReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_videoCore_service_v1_comment_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountComment4UserReq.ProtoReflect.Descriptor instead.
func (*CountComment4UserReq) Descriptor() ([]byte, []int) {
	return file_api_videoCore_service_v1_comment_proto_rawDescGZIP(), []int{14}
}

func (x *CountComment4UserReq) GetUserId() []string {
	if x != nil {
		return x.UserId
	}
	return nil
}

type CountComment4UserResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *Metadata              `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Results       []*CountResult         `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountComment4UserResp) Reset() {
	*x = CountComment4UserResp{}
	mi := &file_api_videoCore_service_v1_comment_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountComment4UserResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountComment4UserResp) ProtoMessage() {}

func (x *CountComment4UserResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_videoCore_service_v1_comment_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountComment4UserResp.ProtoReflect.Descriptor instead.
func (*CountComment4UserResp) Descriptor() ([]byte, []int) {
	return file_api_videoCore_service_v1_comment_proto_rawDescGZIP(), []int{15}
}

func (x *CountComment4UserResp) GetMeta() *Metadata {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *CountComment4UserResp) GetResults() []*CountResult {
	if x != nil {
		return x.Results
	}
	return nil
}

var File_api_videoCore_service_v1_comment_proto protoreflect.FileDescriptor

const file_api_videoCore_service_v1_comment_proto_rawDesc = "" +
	"\n" +
	"&api/videoCore/service/v1/comment.proto\x12\x18api.videoCore.service.v1\x1a#api/videoCore/service/v1/base.proto\"\xbb\x02\n" +
	"\aComment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bvideo_id\x18\x02 \x01(\tR\avideoId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x12\n" +
	"\x04date\x18\x04 \x01(\tR\x04date\x12\x1d\n" +
	"\n" +
	"like_count\x18\x05 \x01(\x03R\tlikeCount\x12\x1f\n" +
	"\vreply_count\x18\x06 \x01(\x03R\n" +
	"replyCount\x12\x17\n" +
	"\auser_id\x18\a \x01(\tR\x06userId\x12\x1b\n" +
	"\tparent_id\x18\b \x01(\tR\bparentId\x12\"\n" +
	"\rreply_user_id\x18\t \x01(\tR\vreplyUserId\x12=\n" +
	"\bcomments\x18\n" +
	" \x03(\v2!.api.videoCore.service.v1.CommentR\bcomments\"\xa1\x01\n" +
	"\x10CreateCommentReq\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\tR\avideoId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1b\n" +
	"\tparent_id\x18\x04 \x01(\tR\bparentId\x12\"\n" +
	"\rreply_user_id\x18\x05 \x01(\tR\vreplyUserId\"\x88\x01\n" +
	"\x11CreateCommentResp\x126\n" +
	"\x04meta\x18\x01 \x01(\v2\".api.videoCore.service.v1.MetadataR\x04meta\x12;\n" +
	"\acomment\x18\x02 \x01(\v2!.api.videoCore.service.v1.CommentR\acomment\"J\n" +
	"\x10RemoveCommentReq\x12\x1d\n" +
	"\n" +
	"comment_id\x18\x01 \x01(\tR\tcommentId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"K\n" +
	"\x11RemoveCommentResp\x126\n" +
	"\x04meta\x18\x01 \x01(\v2\".api.videoCore.service.v1.MetadataR\x04meta\"x\n" +
	"\x14ListComment4VideoReq\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\tR\avideoId\x12E\n" +
	"\n" +
	"page_stats\x18\x02 \x01(\v2&.api.videoCore.service.v1.PageStatsReqR\tpageStats\"\xdd\x01\n" +
	"\x15ListComment4VideoResp\x126\n" +
	"\x04meta\x18\x01 \x01(\v2\".api.videoCore.service.v1.MetadataR\x04meta\x12D\n" +
	"\fcomment_list\x18\x02 \x03(\v2!.api.videoCore.service.v1.CommentR\vcommentList\x12F\n" +
	"\n" +
	"page_stats\x18\x03 \x01(\v2'.api.videoCore.service.v1.PageStatsRespR\tpageStats\"\x83\x01\n" +
	"\x1bListChildComment4CommentReq\x12\x1d\n" +
	"\n" +
	"comment_id\x18\x01 \x01(\tR\tcommentId\x12E\n" +
	"\n" +
	"page_stats\x18\x02 \x01(\v2&.api.videoCore.service.v1.PageStatsReqR\tpageStats\"\xe4\x01\n" +
	"\x1cListChildComment4CommentResp\x126\n" +
	"\x04meta\x18\x01 \x01(\v2\".api.videoCore.service.v1.MetadataR\x04meta\x12D\n" +
	"\fcomment_list\x18\x02 \x03(\v2!.api.videoCore.service.v1.CommentR\vcommentList\x12F\n" +
	"\n" +
	"page_stats\x18\x03 \x01(\v2'.api.videoCore.service.v1.PageStatsRespR\tpageStats\"2\n" +
	"\x11GetCommentByIdReq\x12\x1d\n" +
	"\n" +
	"comment_id\x18\x01 \x01(\tR\tcommentId\"\x89\x01\n" +
	"\x12GetCommentByIdResp\x126\n" +
	"\x04meta\x18\x01 \x01(\v2\".api.videoCore.service.v1.MetadataR\x04meta\x12;\n" +
	"\acomment\x18\x02 \x01(\v2!.api.videoCore.service.v1.CommentR\acomment\"3\n" +
	"\vCountResult\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count\"2\n" +
	"\x15CountComment4VideoReq\x12\x19\n" +
	"\bvideo_id\x18\x01 \x03(\tR\avideoId\"\x91\x01\n" +
	"\x16CountComment4VideoResp\x126\n" +
	"\x04meta\x18\x01 \x01(\v2\".api.videoCore.service.v1.MetadataR\x04meta\x12?\n" +
	"\aresults\x18\x02 \x03(\v2%.api.videoCore.service.v1.CountResultR\aresults\"/\n" +
	"\x14CountComment4UserReq\x12\x17\n" +
	"\auser_id\x18\x01 \x03(\tR\x06userId\"\x90\x01\n" +
	"\x15CountComment4UserResp\x126\n" +
	"\x04meta\x18\x01 \x01(\v2\".api.videoCore.service.v1.MetadataR\x04meta\x12?\n" +
	"\aresults\x18\x02 \x03(\v2%.api.videoCore.service.v1.CountResultR\aresults2\xc2\x06\n" +
	"\x0eCommentService\x12h\n" +
	"\rCreateComment\x12*.api.videoCore.service.v1.CreateCommentReq\x1a+.api.videoCore.service.v1.CreateCommentResp\x12h\n" +
	"\rRemoveComment\x12*.api.videoCore.service.v1.RemoveCommentReq\x1a+.api.videoCore.service.v1.RemoveCommentResp\x12t\n" +
	"\x11ListComment4Video\x12..api.videoCore.service.v1.ListComment4VideoReq\x1a/.api.videoCore.service.v1.ListComment4VideoResp\x12\x89\x01\n" +
	"\x18ListChildComment4Comment\x125.api.videoCore.service.v1.ListChildComment4CommentReq\x1a6.api.videoCore.service.v1.ListChildComment4CommentResp\x12k\n" +
	"\x0eGetCommentById\x12+.api.videoCore.service.v1.GetCommentByIdReq\x1a,.api.videoCore.service.v1.GetCommentByIdResp\x12w\n" +
	"\x12CountComment4Video\x12/.api.videoCore.service.v1.CountComment4VideoReq\x1a0.api.videoCore.service.v1.CountComment4VideoResp\x12t\n" +
	"\x11CountComment4User\x12..api.videoCore.service.v1.CountComment4UserReq\x1a/.api.videoCore.service.v1.CountComment4UserRespBD\n" +
	"\x18api.videoCore.service.v1P\x01Z&lehu-video/api/videoCore/service/v1;v1b\x06proto3"

var (
	file_api_videoCore_service_v1_comment_proto_rawDescOnce sync.Once
	file_api_videoCore_service_v1_comment_proto_rawDescData []byte
)

func file_api_videoCore_service_v1_comment_proto_rawDescGZIP() []byte {
	file_api_videoCore_service_v1_comment_proto_rawDescOnce.Do(func() {
		file_api_videoCore_service_v1_comment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_videoCore_service_v1_comment_proto_rawDesc), len(file_api_videoCore_service_v1_comment_proto_rawDesc)))
	})
	return file_api_videoCore_service_v1_comment_proto_rawDescData
}

var file_api_videoCore_service_v1_comment_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_api_videoCore_service_v1_comment_proto_goTypes = []any{
	(*Comment)(nil),                      // 0: api.videoCore.service.v1.Comment
	(*CreateCommentReq)(nil),             // 1: api.videoCore.service.v1.CreateCommentReq
	(*CreateCommentResp)(nil),            // 2: api.videoCore.service.v1.CreateCommentResp
	(*RemoveCommentReq)(nil),             // 3: api.videoCore.service.v1.RemoveCommentReq
	(*RemoveCommentResp)(nil),            // 4: api.videoCore.service.v1.RemoveCommentResp
	(*ListComment4VideoReq)(nil),         // 5: api.videoCore.service.v1.ListComment4VideoReq
	(*ListComment4VideoResp)(nil),        // 6: api.videoCore.service.v1.ListComment4VideoResp
	(*ListChildComment4CommentReq)(nil),  // 7: api.videoCore.service.v1.ListChildComment4CommentReq
	(*ListChildComment4CommentResp)(nil), // 8: api.videoCore.service.v1.ListChildComment4CommentResp
	(*GetCommentByIdReq)(nil),            // 9: api.videoCore.service.v1.GetCommentByIdReq
	(*GetCommentByIdResp)(nil),           // 10: api.videoCore.service.v1.GetCommentByIdResp
	(*CountResult)(nil),                  // 11: api.videoCore.service.v1.CountResult
	(*CountComment4VideoReq)(nil),        // 12: api.videoCore.service.v1.CountComment4VideoReq
	(*CountComment4VideoResp)(nil),       // 13: api.videoCore.service.v1.CountComment4VideoResp
	(*CountComment4UserReq)(nil),         // 14: api.videoCore.service.v1.CountComment4UserReq
	(*CountComment4UserResp)(nil),        // 15: api.videoCore.service.v1.CountComment4UserResp
	(*Metadata)(nil),                     // 16: api.videoCore.service.v1.Metadata
	(*PageStatsReq)(nil),                 // 17: api.videoCore.service.v1.PageStatsReq
	(*PageStatsResp)(nil),                // 18: api.videoCore.service.v1.PageStatsResp
}
var file_api_videoCore_service_v1_comment_proto_depIdxs = []int32{
	0,  // 0: api.videoCore.service.v1.Comment.comments:type_name -> api.videoCore.service.v1.Comment
	16, // 1: api.videoCore.service.v1.CreateCommentResp.meta:type_name -> api.videoCore.service.v1.Metadata
	0,  // 2: api.videoCore.service.v1.CreateCommentResp.comment:type_name -> api.videoCore.service.v1.Comment
	16, // 3: api.videoCore.service.v1.RemoveCommentResp.meta:type_name -> api.videoCore.service.v1.Metadata
	17, // 4: api.videoCore.service.v1.ListComment4VideoReq.page_stats:type_name -> api.videoCore.service.v1.PageStatsReq
	16, // 5: api.videoCore.service.v1.ListComment4VideoResp.meta:type_name -> api.videoCore.service.v1.Metadata
	0,  // 6: api.videoCore.service.v1.ListComment4VideoResp.comment_list:type_name -> api.videoCore.service.v1.Comment
	18, // 7: api.videoCore.service.v1.ListComment4VideoResp.page_stats:type_name -> api.videoCore.service.v1.PageStatsResp
	17, // 8: api.videoCore.service.v1.ListChildComment4CommentReq.page_stats:type_name -> api.videoCore.service.v1.PageStatsReq
	16, // 9: api.videoCore.service.v1.ListChildComment4CommentResp.meta:type_name -> api.videoCore.service.v1.Metadata
	0,  // 10: api.videoCore.service.v1.ListChildComment4CommentResp.comment_list:type_name -> api.videoCore.service.v1.Comment
	18, // 11: api.videoCore.service.v1.ListChildComment4CommentResp.page_stats:type_name -> api.videoCore.service.v1.PageStatsResp
	16, // 12: api.videoCore.service.v1.GetCommentByIdResp.meta:type_name -> api.videoCore.service.v1.Metadata
	0,  // 13: api.videoCore.service.v1.GetCommentByIdResp.comment:type_name -> api.videoCore.service.v1.Comment
	16, // 14: api.videoCore.service.v1.CountComment4VideoResp.meta:type_name -> api.videoCore.service.v1.Metadata
	11, // 15: api.videoCore.service.v1.CountComment4VideoResp.results:type_name -> api.videoCore.service.v1.CountResult
	16, // 16: api.videoCore.service.v1.CountComment4UserResp.meta:type_name -> api.videoCore.service.v1.Metadata
	11, // 17: api.videoCore.service.v1.CountComment4UserResp.results:type_name -> api.videoCore.service.v1.CountResult
	1,  // 18: api.videoCore.service.v1.CommentService.CreateComment:input_type -> api.videoCore.service.v1.CreateCommentReq
	3,  // 19: api.videoCore.service.v1.CommentService.RemoveComment:input_type -> api.videoCore.service.v1.RemoveCommentReq
	5,  // 20: api.videoCore.service.v1.CommentService.ListComment4Video:input_type -> api.videoCore.service.v1.ListComment4VideoReq
	7,  // 21: api.videoCore.service.v1.CommentService.ListChildComment4Comment:input_type -> api.videoCore.service.v1.ListChildComment4CommentReq
	9,  // 22: api.videoCore.service.v1.CommentService.GetCommentById:input_type -> api.videoCore.service.v1.GetCommentByIdReq
	12, // 23: api.videoCore.service.v1.CommentService.CountComment4Video:input_type -> api.videoCore.service.v1.CountComment4VideoReq
	14, // 24: api.videoCore.service.v1.CommentService.CountComment4User:input_type -> api.videoCore.service.v1.CountComment4UserReq
	2,  // 25: api.videoCore.service.v1.CommentService.CreateComment:output_type -> api.videoCore.service.v1.CreateCommentResp
	4,  // 26: api.videoCore.service.v1.CommentService.RemoveComment:output_type -> api.videoCore.service.v1.RemoveCommentResp
	6,  // 27: api.videoCore.service.v1.CommentService.ListComment4Video:output_type -> api.videoCore.service.v1.ListComment4VideoResp
	8,  // 28: api.videoCore.service.v1.CommentService.ListChildComment4Comment:output_type -> api.videoCore.service.v1.ListChildComment4CommentResp
	10, // 29: api.videoCore.service.v1.CommentService.GetCommentById:output_type -> api.videoCore.service.v1.GetCommentByIdResp
	13, // 30: api.videoCore.service.v1.CommentService.CountComment4Video:output_type -> api.videoCore.service.v1.CountComment4VideoResp
	15, // 31: api.videoCore.service.v1.CommentService.CountComment4User:output_type -> api.videoCore.service.v1.CountComment4UserResp
	25, // [25:32] is the sub-list for method output_type
	18, // [18:25] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_api_videoCore_service_v1_comment_proto_init() }
func file_api_videoCore_service_v1_comment_proto_init() {
	if File_api_videoCore_service_v1_comment_proto != nil {
		return
	}
	file_api_videoCore_service_v1_base_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_videoCore_service_v1_comment_proto_rawDesc), len(file_api_videoCore_service_v1_comment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_videoCore_service_v1_comment_proto_goTypes,
		DependencyIndexes: file_api_videoCore_service_v1_comment_proto_depIdxs,
		MessageInfos:      file_api_videoCore_service_v1_comment_proto_msgTypes,
	}.Build()
	File_api_videoCore_service_v1_comment_proto = out.File
	file_api_videoCore_service_v1_comment_proto_goTypes = nil
	file_api_videoCore_service_v1_comment_proto_depIdxs = nil
}
