// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.20.3
// source: api/videoCore/service/v1/user.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateUserImageType int32

const (
	UpdateUserImageType_AVATAR           UpdateUserImageType = 0
	UpdateUserImageType_BACKGROUND_IMAGE UpdateUserImageType = 1
)

// Enum value maps for UpdateUserImageType.
var (
	UpdateUserImageType_name = map[int32]string{
		0: "AVATAR",
		1: "BACKGROUND_IMAGE",
	}
	UpdateUserImageType_value = map[string]int32{
		"AVATAR":           0,
		"BACKGROUND_IMAGE": 1,
	}
)

func (x UpdateUserImageType) Enum() *UpdateUserImageType {
	p := new(UpdateUserImageType)
	*p = x
	return p
}

func (x UpdateUserImageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UpdateUserImageType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_videoCore_service_v1_user_proto_enumTypes[0].Descriptor()
}

func (UpdateUserImageType) Type() protoreflect.EnumType {
	return &file_api_videoCore_service_v1_user_proto_enumTypes[0]
}

func (x UpdateUserImageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UpdateUserImageType.Descriptor instead.
func (UpdateUserImageType) EnumDescriptor() ([]byte, []int) {
	return file_api_videoCore_service_v1_user_proto_rawDescGZIP(), []int{0}
}

type User struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                                  // 用户id
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                              // 用户名称
	Avatar          string                 `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`                                          // 用户头像Url
	BackgroundImage string                 `protobuf:"bytes,4,opt,name=background_image,json=backgroundImage,proto3" json:"background_image,omitempty"` // 用户个人页顶部大图
	Signature       string                 `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`                                    // 个人简介
	Mobile          string                 `protobuf:"bytes,6,opt,name=mobile,proto3" json:"mobile,omitempty"`                                          // 手机号
	Email           string                 `protobuf:"bytes,7,opt,name=email,proto3" json:"email,omitempty"`                                            // 邮箱
	FollowCount     int64                  `protobuf:"varint,8,opt,name=follow_count,json=followCount,proto3" json:"follow_count,omitempty"`            // 关注总数
	FollowerCount   int64                  `protobuf:"varint,9,opt,name=follower_count,json=followerCount,proto3" json:"follower_count,omitempty"`      // 粉丝总数
	TotalFavorited  int64                  `protobuf:"varint,10,opt,name=total_favorited,json=totalFavorited,proto3" json:"total_favorited,omitempty"`  // 获赞数量
	WorkCount       int64                  `protobuf:"varint,11,opt,name=work_count,json=workCount,proto3" json:"work_count,omitempty"`                 // 作品数量
	FavoriteCount   int64                  `protobuf:"varint,12,opt,name=favorite_count,json=favoriteCount,proto3" json:"favorite_count,omitempty"`     // 点赞数量
	Nickname        string                 `protobuf:"bytes,13,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Gender          int32                  `protobuf:"varint,14,opt,name=gender,proto3" json:"gender,omitempty"`
	OnlineStatus    int32                  `protobuf:"varint,15,opt,name=online_status,json=onlineStatus,proto3" json:"online_status,omitempty"`
	LastOnlineTime  string                 `protobuf:"bytes,16,opt,name=last_online_time,json=lastOnlineTime,proto3" json:"last_online_time,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_api_videoCore_service_v1_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_api_videoCore_service_v1_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_api_videoCore_service_v1_user_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *User) GetBackgroundImage() string {
	if x != nil {
		return x.BackgroundImage
	}
	return ""
}

func (x *User) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *User) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetFollowCount() int64 {
	if x != nil {
		return x.FollowCount
	}
	return 0
}

func (x *User) GetFollowerCount() int64 {
	if x != nil {
		return x.FollowerCount
	}
	return 0
}

func (x *User) GetTotalFavorited() int64 {
	if x != nil {
		return x.TotalFavorited
	}
	return 0
}

func (x *User) GetWorkCount() int64 {
	if x != nil {
		return x.WorkCount
	}
	return 0
}

func (x *User) GetFavoriteCount() int64 {
	if x != nil {
		return x.FavoriteCount
	}
	return 0
}

func (x *User) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *User) GetGender() int32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *User) GetOnlineStatus() int32 {
	if x != nil {
		return x.OnlineStatus
	}
	return 0
}

func (x *User) GetLastOnlineTime() string {
	if x != nil {
		return x.LastOnlineTime
	}
	return ""
}

type CreateUserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mobile        string                 `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	AccountId     string                 `protobuf:"bytes,3,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserReq) Reset() {
	*x = CreateUserReq{}
	mi := &file_api_videoCore_service_v1_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserReq) ProtoMessage() {}

func (x *CreateUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_videoCore_service_v1_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserReq.ProtoReflect.Descriptor instead.
func (*CreateUserReq) Descriptor() ([]byte, []int) {
	return file_api_videoCore_service_v1_user_proto_rawDescGZIP(), []int{1}
}

func (x *CreateUserReq) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *CreateUserReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateUserReq) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type CreateUserResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *Metadata              `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserResp) Reset() {
	*x = CreateUserResp{}
	mi := &file_api_videoCore_service_v1_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserResp) ProtoMessage() {}

func (x *CreateUserResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_videoCore_service_v1_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserResp.ProtoReflect.Descriptor instead.
func (*CreateUserResp) Descriptor() ([]byte, []int) {
	return file_api_videoCore_service_v1_user_proto_rawDescGZIP(), []int{2}
}

func (x *CreateUserResp) GetMeta() *Metadata {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *CreateUserResp) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AccountId     string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInfoReq) Reset() {
	*x = GetUserInfoReq{}
	mi := &file_api_videoCore_service_v1_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoReq) ProtoMessage() {}

func (x *GetUserInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_videoCore_service_v1_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoReq.ProtoReflect.Descriptor instead.
func (*GetUserInfoReq) Descriptor() ([]byte, []int) {
	return file_api_videoCore_service_v1_user_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserInfoReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUserInfoReq) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type GetUserInfoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *Metadata              `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	User          *User                  `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInfoResp) Reset() {
	*x = GetUserInfoResp{}
	mi := &file_api_videoCore_service_v1_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoResp) ProtoMessage() {}

func (x *GetUserInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_videoCore_service_v1_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoResp.ProtoReflect.Descriptor instead.
func (*GetUserInfoResp) Descriptor() ([]byte, []int) {
	return file_api_videoCore_service_v1_user_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserInfoResp) GetMeta() *Metadata {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *GetUserInfoResp) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type UpdateUserInfoReq struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Avatar          string                 `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	BackgroundImage string                 `protobuf:"bytes,4,opt,name=background_image,json=backgroundImage,proto3" json:"background_image,omitempty"`
	Signature       string                 `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateUserInfoReq) Reset() {
	*x = UpdateUserInfoReq{}
	mi := &file_api_videoCore_service_v1_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserInfoReq) ProtoMessage() {}

func (x *UpdateUserInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_videoCore_service_v1_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserInfoReq.ProtoReflect.Descriptor instead.
func (*UpdateUserInfoReq) Descriptor() ([]byte, []int) {
	return file_api_videoCore_service_v1_user_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateUserInfoReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateUserInfoReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateUserInfoReq) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *UpdateUserInfoReq) GetBackgroundImage() string {
	if x != nil {
		return x.BackgroundImage
	}
	return ""
}

func (x *UpdateUserInfoReq) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

type UpdateUserInfoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *Metadata              `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserInfoResp) Reset() {
	*x = UpdateUserInfoResp{}
	mi := &file_api_videoCore_service_v1_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserInfoResp) ProtoMessage() {}

func (x *UpdateUserInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_videoCore_service_v1_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserInfoResp.ProtoReflect.Descriptor instead.
func (*UpdateUserInfoResp) Descriptor() ([]byte, []int) {
	return file_api_videoCore_service_v1_user_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateUserInfoResp) GetMeta() *Metadata {
	if x != nil {
		return x.Meta
	}
	return nil
}

type GetUserByIdListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIdList    []string               `protobuf:"bytes,1,rep,name=user_id_list,json=userIdList,proto3" json:"user_id_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByIdListReq) Reset() {
	*x = GetUserByIdListReq{}
	mi := &file_api_videoCore_service_v1_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByIdListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByIdListReq) ProtoMessage() {}

func (x *GetUserByIdListReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_videoCore_service_v1_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByIdListReq.ProtoReflect.Descriptor instead.
func (*GetUserByIdListReq) Descriptor() ([]byte, []int) {
	return file_api_videoCore_service_v1_user_proto_rawDescGZIP(), []int{7}
}

func (x *GetUserByIdListReq) GetUserIdList() []string {
	if x != nil {
		return x.UserIdList
	}
	return nil
}

type GetUserByIdListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserList      []*User                `protobuf:"bytes,1,rep,name=user_list,json=userList,proto3" json:"user_list,omitempty"`
	Meta          *Metadata              `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByIdListResp) Reset() {
	*x = GetUserByIdListResp{}
	mi := &file_api_videoCore_service_v1_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByIdListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByIdListResp) ProtoMessage() {}

func (x *GetUserByIdListResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_videoCore_service_v1_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByIdListResp.ProtoReflect.Descriptor instead.
func (*GetUserByIdListResp) Descriptor() ([]byte, []int) {
	return file_api_videoCore_service_v1_user_proto_rawDescGZIP(), []int{8}
}

func (x *GetUserByIdListResp) GetUserList() []*User {
	if x != nil {
		return x.UserList
	}
	return nil
}

func (x *GetUserByIdListResp) GetMeta() *Metadata {
	if x != nil {
		return x.Meta
	}
	return nil
}

// 新增：搜索用户请求
type SearchUsersReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keyword       string                 `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchUsersReq) Reset() {
	*x = SearchUsersReq{}
	mi := &file_api_videoCore_service_v1_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchUsersReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchUsersReq) ProtoMessage() {}

func (x *SearchUsersReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_videoCore_service_v1_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchUsersReq.ProtoReflect.Descriptor instead.
func (*SearchUsersReq) Descriptor() ([]byte, []int) {
	return file_api_videoCore_service_v1_user_proto_rawDescGZIP(), []int{9}
}

func (x *SearchUsersReq) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *SearchUsersReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchUsersReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// 新增：搜索用户响应
type SearchUsersResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Meta          *Metadata              `protobuf:"bytes,3,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchUsersResp) Reset() {
	*x = SearchUsersResp{}
	mi := &file_api_videoCore_service_v1_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchUsersResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchUsersResp) ProtoMessage() {}

func (x *SearchUsersResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_videoCore_service_v1_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchUsersResp.ProtoReflect.Descriptor instead.
func (*SearchUsersResp) Descriptor() ([]byte, []int) {
	return file_api_videoCore_service_v1_user_proto_rawDescGZIP(), []int{10}
}

func (x *SearchUsersResp) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *SearchUsersResp) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *SearchUsersResp) GetMeta() *Metadata {
	if x != nil {
		return x.Meta
	}
	return nil
}

var File_api_videoCore_service_v1_user_proto protoreflect.FileDescriptor

const file_api_videoCore_service_v1_user_proto_rawDesc = "" +
	"\n" +
	"#api/videoCore/service/v1/user.proto\x12\x18api.videoCore.service.v1\x1a\x1cgoogle/api/annotations.proto\x1a#api/videoCore/service/v1/base.proto\"\xf5\x03\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\x12)\n" +
	"\x10background_image\x18\x04 \x01(\tR\x0fbackgroundImage\x12\x1c\n" +
	"\tsignature\x18\x05 \x01(\tR\tsignature\x12\x16\n" +
	"\x06mobile\x18\x06 \x01(\tR\x06mobile\x12\x14\n" +
	"\x05email\x18\a \x01(\tR\x05email\x12!\n" +
	"\ffollow_count\x18\b \x01(\x03R\vfollowCount\x12%\n" +
	"\x0efollower_count\x18\t \x01(\x03R\rfollowerCount\x12'\n" +
	"\x0ftotal_favorited\x18\n" +
	" \x01(\x03R\x0etotalFavorited\x12\x1d\n" +
	"\n" +
	"work_count\x18\v \x01(\x03R\tworkCount\x12%\n" +
	"\x0efavorite_count\x18\f \x01(\x03R\rfavoriteCount\x12\x1a\n" +
	"\bnickname\x18\r \x01(\tR\bnickname\x12\x16\n" +
	"\x06gender\x18\x0e \x01(\x05R\x06gender\x12#\n" +
	"\ronline_status\x18\x0f \x01(\x05R\fonlineStatus\x12(\n" +
	"\x10last_online_time\x18\x10 \x01(\tR\x0elastOnlineTime\"\\\n" +
	"\rCreateUserReq\x12\x16\n" +
	"\x06mobile\x18\x01 \x01(\tR\x06mobile\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"account_id\x18\x03 \x01(\tR\taccountId\"a\n" +
	"\x0eCreateUserResp\x126\n" +
	"\x04meta\x18\x01 \x01(\v2\".api.videoCore.service.v1.MetadataR\x04meta\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"H\n" +
	"\x0eGetUserInfoReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\"}\n" +
	"\x0fGetUserInfoResp\x126\n" +
	"\x04meta\x18\x01 \x01(\v2\".api.videoCore.service.v1.MetadataR\x04meta\x122\n" +
	"\x04user\x18\x02 \x01(\v2\x1e.api.videoCore.service.v1.UserR\x04user\"\xa1\x01\n" +
	"\x11UpdateUserInfoReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\x12)\n" +
	"\x10background_image\x18\x04 \x01(\tR\x0fbackgroundImage\x12\x1c\n" +
	"\tsignature\x18\x05 \x01(\tR\tsignature\"L\n" +
	"\x12UpdateUserInfoResp\x126\n" +
	"\x04meta\x18\x01 \x01(\v2\".api.videoCore.service.v1.MetadataR\x04meta\"6\n" +
	"\x12GetUserByIdListReq\x12 \n" +
	"\fuser_id_list\x18\x01 \x03(\tR\n" +
	"userIdList\"\x8a\x01\n" +
	"\x13GetUserByIdListResp\x12;\n" +
	"\tuser_list\x18\x01 \x03(\v2\x1e.api.videoCore.service.v1.UserR\buserList\x126\n" +
	"\x04meta\x18\x02 \x01(\v2\".api.videoCore.service.v1.MetadataR\x04meta\"[\n" +
	"\x0eSearchUsersReq\x12\x18\n" +
	"\akeyword\x18\x01 \x01(\tR\akeyword\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"\x95\x01\n" +
	"\x0fSearchUsersResp\x124\n" +
	"\x05users\x18\x01 \x03(\v2\x1e.api.videoCore.service.v1.UserR\x05users\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x126\n" +
	"\x04meta\x18\x03 \x01(\v2\".api.videoCore.service.v1.MetadataR\x04meta*7\n" +
	"\x13UpdateUserImageType\x12\n" +
	"\n" +
	"\x06AVATAR\x10\x00\x12\x14\n" +
	"\x10BACKGROUND_IMAGE\x10\x012\xd0\x04\n" +
	"\vUserService\x12t\n" +
	"\n" +
	"CreateUser\x12'.api.videoCore.service.v1.CreateUserReq\x1a(.api.videoCore.service.v1.CreateUserResp\"\x13\x82\xd3\xe4\x93\x02\r:\x01*\"\b/v1/user\x12~\n" +
	"\n" +
	"UpdateUser\x12+.api.videoCore.service.v1.UpdateUserInfoReq\x1a,.api.videoCore.service.v1.UpdateUserInfoResp\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/v1/user/info\x12w\n" +
	"\vGetUserInfo\x12(.api.videoCore.service.v1.GetUserInfoReq\x1a).api.videoCore.service.v1.GetUserInfoResp\"\x13\x82\xd3\xe4\x93\x02\r:\x01*\x1a\b/v1/user\x12n\n" +
	"\x0fGetUserByIdList\x12,.api.videoCore.service.v1.GetUserByIdListReq\x1a-.api.videoCore.service.v1.GetUserByIdListResp\x12b\n" +
	"\vSearchUsers\x12(.api.videoCore.service.v1.SearchUsersReq\x1a).api.videoCore.service.v1.SearchUsersRespBD\n" +
	"\x18api.videoCore.service.v1P\x01Z&lehu-video/api/videoCore/service/v1;v1b\x06proto3"

var (
	file_api_videoCore_service_v1_user_proto_rawDescOnce sync.Once
	file_api_videoCore_service_v1_user_proto_rawDescData []byte
)

func file_api_videoCore_service_v1_user_proto_rawDescGZIP() []byte {
	file_api_videoCore_service_v1_user_proto_rawDescOnce.Do(func() {
		file_api_videoCore_service_v1_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_videoCore_service_v1_user_proto_rawDesc), len(file_api_videoCore_service_v1_user_proto_rawDesc)))
	})
	return file_api_videoCore_service_v1_user_proto_rawDescData
}

var file_api_videoCore_service_v1_user_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_videoCore_service_v1_user_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_api_videoCore_service_v1_user_proto_goTypes = []any{
	(UpdateUserImageType)(0),    // 0: api.videoCore.service.v1.UpdateUserImageType
	(*User)(nil),                // 1: api.videoCore.service.v1.User
	(*CreateUserReq)(nil),       // 2: api.videoCore.service.v1.CreateUserReq
	(*CreateUserResp)(nil),      // 3: api.videoCore.service.v1.CreateUserResp
	(*GetUserInfoReq)(nil),      // 4: api.videoCore.service.v1.GetUserInfoReq
	(*GetUserInfoResp)(nil),     // 5: api.videoCore.service.v1.GetUserInfoResp
	(*UpdateUserInfoReq)(nil),   // 6: api.videoCore.service.v1.UpdateUserInfoReq
	(*UpdateUserInfoResp)(nil),  // 7: api.videoCore.service.v1.UpdateUserInfoResp
	(*GetUserByIdListReq)(nil),  // 8: api.videoCore.service.v1.GetUserByIdListReq
	(*GetUserByIdListResp)(nil), // 9: api.videoCore.service.v1.GetUserByIdListResp
	(*SearchUsersReq)(nil),      // 10: api.videoCore.service.v1.SearchUsersReq
	(*SearchUsersResp)(nil),     // 11: api.videoCore.service.v1.SearchUsersResp
	(*Metadata)(nil),            // 12: api.videoCore.service.v1.Metadata
}
var file_api_videoCore_service_v1_user_proto_depIdxs = []int32{
	12, // 0: api.videoCore.service.v1.CreateUserResp.meta:type_name -> api.videoCore.service.v1.Metadata
	12, // 1: api.videoCore.service.v1.GetUserInfoResp.meta:type_name -> api.videoCore.service.v1.Metadata
	1,  // 2: api.videoCore.service.v1.GetUserInfoResp.user:type_name -> api.videoCore.service.v1.User
	12, // 3: api.videoCore.service.v1.UpdateUserInfoResp.meta:type_name -> api.videoCore.service.v1.Metadata
	1,  // 4: api.videoCore.service.v1.GetUserByIdListResp.user_list:type_name -> api.videoCore.service.v1.User
	12, // 5: api.videoCore.service.v1.GetUserByIdListResp.meta:type_name -> api.videoCore.service.v1.Metadata
	1,  // 6: api.videoCore.service.v1.SearchUsersResp.users:type_name -> api.videoCore.service.v1.User
	12, // 7: api.videoCore.service.v1.SearchUsersResp.meta:type_name -> api.videoCore.service.v1.Metadata
	2,  // 8: api.videoCore.service.v1.UserService.CreateUser:input_type -> api.videoCore.service.v1.CreateUserReq
	6,  // 9: api.videoCore.service.v1.UserService.UpdateUser:input_type -> api.videoCore.service.v1.UpdateUserInfoReq
	4,  // 10: api.videoCore.service.v1.UserService.GetUserInfo:input_type -> api.videoCore.service.v1.GetUserInfoReq
	8,  // 11: api.videoCore.service.v1.UserService.GetUserByIdList:input_type -> api.videoCore.service.v1.GetUserByIdListReq
	10, // 12: api.videoCore.service.v1.UserService.SearchUsers:input_type -> api.videoCore.service.v1.SearchUsersReq
	3,  // 13: api.videoCore.service.v1.UserService.CreateUser:output_type -> api.videoCore.service.v1.CreateUserResp
	7,  // 14: api.videoCore.service.v1.UserService.UpdateUser:output_type -> api.videoCore.service.v1.UpdateUserInfoResp
	5,  // 15: api.videoCore.service.v1.UserService.GetUserInfo:output_type -> api.videoCore.service.v1.GetUserInfoResp
	9,  // 16: api.videoCore.service.v1.UserService.GetUserByIdList:output_type -> api.videoCore.service.v1.GetUserByIdListResp
	11, // 17: api.videoCore.service.v1.UserService.SearchUsers:output_type -> api.videoCore.service.v1.SearchUsersResp
	13, // [13:18] is the sub-list for method output_type
	8,  // [8:13] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_api_videoCore_service_v1_user_proto_init() }
func file_api_videoCore_service_v1_user_proto_init() {
	if File_api_videoCore_service_v1_user_proto != nil {
		return
	}
	file_api_videoCore_service_v1_base_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_videoCore_service_v1_user_proto_rawDesc), len(file_api_videoCore_service_v1_user_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_videoCore_service_v1_user_proto_goTypes,
		DependencyIndexes: file_api_videoCore_service_v1_user_proto_depIdxs,
		EnumInfos:         file_api_videoCore_service_v1_user_proto_enumTypes,
		MessageInfos:      file_api_videoCore_service_v1_user_proto_msgTypes,
	}.Build()
	File_api_videoCore_service_v1_user_proto = out.File
	file_api_videoCore_service_v1_user_proto_goTypes = nil
	file_api_videoCore_service_v1_user_proto_depIdxs = nil
}
