// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.20.3
// source: api/videoChat/service/v1/base.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Metadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          string                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Reason        []string               `protobuf:"bytes,4,rep,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_api_videoChat_service_v1_base_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_api_videoChat_service_v1_base_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_api_videoChat_service_v1_base_proto_rawDescGZIP(), []int{0}
}

func (x *Metadata) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Metadata) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Metadata) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *Metadata) GetReason() []string {
	if x != nil {
		return x.Reason
	}
	return nil
}

type PageStatsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size          int32                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Sort          string                 `protobuf:"bytes,3,opt,name=sort,proto3" json:"sort,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageStatsReq) Reset() {
	*x = PageStatsReq{}
	mi := &file_api_videoChat_service_v1_base_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageStatsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageStatsReq) ProtoMessage() {}

func (x *PageStatsReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_videoChat_service_v1_base_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageStatsReq.ProtoReflect.Descriptor instead.
func (*PageStatsReq) Descriptor() ([]byte, []int) {
	return file_api_videoChat_service_v1_base_proto_rawDescGZIP(), []int{1}
}

func (x *PageStatsReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PageStatsReq) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *PageStatsReq) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

type PageStatsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageStatsResp) Reset() {
	*x = PageStatsResp{}
	mi := &file_api_videoChat_service_v1_base_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageStatsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageStatsResp) ProtoMessage() {}

func (x *PageStatsResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_videoChat_service_v1_base_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageStatsResp.ProtoReflect.Descriptor instead.
func (*PageStatsResp) Descriptor() ([]byte, []int) {
	return file_api_videoChat_service_v1_base_proto_rawDescGZIP(), []int{2}
}

func (x *PageStatsResp) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_api_videoChat_service_v1_base_proto protoreflect.FileDescriptor

const file_api_videoChat_service_v1_base_proto_rawDesc = "" +
	"\n" +
	"#api/videoChat/service/v1/base.proto\x12\x18api.videoChat.service.v1\"d\n" +
	"\bMetadata\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x12\n" +
	"\x04data\x18\x03 \x01(\tR\x04data\x12\x16\n" +
	"\x06reason\x18\x04 \x03(\tR\x06reason\"J\n" +
	"\fPageStatsReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x05R\x04size\x12\x12\n" +
	"\x04sort\x18\x03 \x01(\tR\x04sort\"%\n" +
	"\rPageStatsResp\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05totalBD\n" +
	"\x18api.videoChat.service.v1P\x01Z&lehu-video/api/videoChat/service/v1;v1b\x06proto3"

var (
	file_api_videoChat_service_v1_base_proto_rawDescOnce sync.Once
	file_api_videoChat_service_v1_base_proto_rawDescData []byte
)

func file_api_videoChat_service_v1_base_proto_rawDescGZIP() []byte {
	file_api_videoChat_service_v1_base_proto_rawDescOnce.Do(func() {
		file_api_videoChat_service_v1_base_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_videoChat_service_v1_base_proto_rawDesc), len(file_api_videoChat_service_v1_base_proto_rawDesc)))
	})
	return file_api_videoChat_service_v1_base_proto_rawDescData
}

var file_api_videoChat_service_v1_base_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_videoChat_service_v1_base_proto_goTypes = []any{
	(*Metadata)(nil),      // 0: api.videoChat.service.v1.Metadata
	(*PageStatsReq)(nil),  // 1: api.videoChat.service.v1.PageStatsReq
	(*PageStatsResp)(nil), // 2: api.videoChat.service.v1.PageStatsResp
}
var file_api_videoChat_service_v1_base_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_videoChat_service_v1_base_proto_init() }
func file_api_videoChat_service_v1_base_proto_init() {
	if File_api_videoChat_service_v1_base_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_videoChat_service_v1_base_proto_rawDesc), len(file_api_videoChat_service_v1_base_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_videoChat_service_v1_base_proto_goTypes,
		DependencyIndexes: file_api_videoChat_service_v1_base_proto_depIdxs,
		MessageInfos:      file_api_videoChat_service_v1_base_proto_msgTypes,
	}.Build()
	File_api_videoChat_service_v1_base_proto = out.File
	file_api_videoChat_service_v1_base_proto_goTypes = nil
	file_api_videoChat_service_v1_base_proto_depIdxs = nil
}
