// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.20.3
// source: api/videoChat/service/v1/message.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 会话类型
type ConversationType int32

const (
	ConversationType_SINGLE ConversationType = 0 // 单聊
	ConversationType_GROUP  ConversationType = 1 // 群聊
)

// Enum value maps for ConversationType.
var (
	ConversationType_name = map[int32]string{
		0: "SINGLE",
		1: "GROUP",
	}
	ConversationType_value = map[string]int32{
		"SINGLE": 0,
		"GROUP":  1,
	}
)

func (x ConversationType) Enum() *ConversationType {
	p := new(ConversationType)
	*p = x
	return p
}

func (x ConversationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConversationType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_videoChat_service_v1_message_proto_enumTypes[0].Descriptor()
}

func (ConversationType) Type() protoreflect.EnumType {
	return &file_api_videoChat_service_v1_message_proto_enumTypes[0]
}

func (x ConversationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConversationType.Descriptor instead.
func (ConversationType) EnumDescriptor() ([]byte, []int) {
	return file_api_videoChat_service_v1_message_proto_rawDescGZIP(), []int{0}
}

// 消息类型
type MessageType int32

const (
	MessageType_TEXT   MessageType = 0
	MessageType_IMAGE  MessageType = 1
	MessageType_VOICE  MessageType = 2
	MessageType_VIDEO  MessageType = 3
	MessageType_FILE   MessageType = 4
	MessageType_SYSTEM MessageType = 99
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0:  "TEXT",
		1:  "IMAGE",
		2:  "VOICE",
		3:  "VIDEO",
		4:  "FILE",
		99: "SYSTEM",
	}
	MessageType_value = map[string]int32{
		"TEXT":   0,
		"IMAGE":  1,
		"VOICE":  2,
		"VIDEO":  3,
		"FILE":   4,
		"SYSTEM": 99,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_videoChat_service_v1_message_proto_enumTypes[1].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_api_videoChat_service_v1_message_proto_enumTypes[1]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_api_videoChat_service_v1_message_proto_rawDescGZIP(), []int{1}
}

// 消息状态
type MessageStatus int32

const (
	MessageStatus_SENDING   MessageStatus = 0
	MessageStatus_SENT      MessageStatus = 1
	MessageStatus_DELIVERED MessageStatus = 2
	MessageStatus_READ      MessageStatus = 3
	MessageStatus_RECALLED  MessageStatus = 4
	MessageStatus_FAILED    MessageStatus = 99
)

// Enum value maps for MessageStatus.
var (
	MessageStatus_name = map[int32]string{
		0:  "SENDING",
		1:  "SENT",
		2:  "DELIVERED",
		3:  "READ",
		4:  "RECALLED",
		99: "FAILED",
	}
	MessageStatus_value = map[string]int32{
		"SENDING":   0,
		"SENT":      1,
		"DELIVERED": 2,
		"READ":      3,
		"RECALLED":  4,
		"FAILED":    99,
	}
)

func (x MessageStatus) Enum() *MessageStatus {
	p := new(MessageStatus)
	*p = x
	return p
}

func (x MessageStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_videoChat_service_v1_message_proto_enumTypes[2].Descriptor()
}

func (MessageStatus) Type() protoreflect.EnumType {
	return &file_api_videoChat_service_v1_message_proto_enumTypes[2]
}

func (x MessageStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageStatus.Descriptor instead.
func (MessageStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_videoChat_service_v1_message_proto_rawDescGZIP(), []int{2}
}

type MessageContent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,2,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	ImageWidth    int64                  `protobuf:"varint,3,opt,name=image_width,json=imageWidth,proto3" json:"image_width,omitempty"`
	ImageHeight   int64                  `protobuf:"varint,4,opt,name=image_height,json=imageHeight,proto3" json:"image_height,omitempty"`
	VoiceUrl      string                 `protobuf:"bytes,5,opt,name=voice_url,json=voiceUrl,proto3" json:"voice_url,omitempty"`
	VoiceDuration int64                  `protobuf:"varint,6,opt,name=voice_duration,json=voiceDuration,proto3" json:"voice_duration,omitempty"`
	VideoUrl      string                 `protobuf:"bytes,7,opt,name=video_url,json=videoUrl,proto3" json:"video_url,omitempty"`
	VideoCover    string                 `protobuf:"bytes,8,opt,name=video_cover,json=videoCover,proto3" json:"video_cover,omitempty"`
	VideoDuration int64                  `protobuf:"varint,9,opt,name=video_duration,json=videoDuration,proto3" json:"video_duration,omitempty"`
	FileUrl       string                 `protobuf:"bytes,10,opt,name=file_url,json=fileUrl,proto3" json:"file_url,omitempty"`
	FileName      string                 `protobuf:"bytes,11,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	FileSize      int64                  `protobuf:"varint,12,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	Extra         string                 `protobuf:"bytes,13,opt,name=extra,proto3" json:"extra,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageContent) Reset() {
	*x = MessageContent{}
	mi := &file_api_videoChat_service_v1_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageContent) ProtoMessage() {}

func (x *MessageContent) ProtoReflect() protoreflect.Message {
	mi := &file_api_videoChat_service_v1_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageContent.ProtoReflect.Descriptor instead.
func (*MessageContent) Descriptor() ([]byte, []int) {
	return file_api_videoChat_service_v1_message_proto_rawDescGZIP(), []int{0}
}

func (x *MessageContent) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *MessageContent) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *MessageContent) GetImageWidth() int64 {
	if x != nil {
		return x.ImageWidth
	}
	return 0
}

func (x *MessageContent) GetImageHeight() int64 {
	if x != nil {
		return x.ImageHeight
	}
	return 0
}

func (x *MessageContent) GetVoiceUrl() string {
	if x != nil {
		return x.VoiceUrl
	}
	return ""
}

func (x *MessageContent) GetVoiceDuration() int64 {
	if x != nil {
		return x.VoiceDuration
	}
	return 0
}

func (x *MessageContent) GetVideoUrl() string {
	if x != nil {
		return x.VideoUrl
	}
	return ""
}

func (x *MessageContent) GetVideoCover() string {
	if x != nil {
		return x.VideoCover
	}
	return ""
}

func (x *MessageContent) GetVideoDuration() int64 {
	if x != nil {
		return x.VideoDuration
	}
	return 0
}

func (x *MessageContent) GetFileUrl() string {
	if x != nil {
		return x.FileUrl
	}
	return ""
}

func (x *MessageContent) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *MessageContent) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *MessageContent) GetExtra() string {
	if x != nil {
		return x.Extra
	}
	return ""
}

type Message struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ConversationId int64                  `protobuf:"varint,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	SenderId       int64                  `protobuf:"varint,3,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	ReceiverId     int64                  `protobuf:"varint,4,opt,name=receiver_id,json=receiverId,proto3" json:"receiver_id,omitempty"` // 用户ID 或 群ID
	ConvType       ConversationType       `protobuf:"varint,5,opt,name=conv_type,json=convType,proto3,enum=api.videoChat.service.v1.ConversationType" json:"conv_type,omitempty"`
	MsgType        MessageType            `protobuf:"varint,6,opt,name=msg_type,json=msgType,proto3,enum=api.videoChat.service.v1.MessageType" json:"msg_type,omitempty"`
	Content        *MessageContent        `protobuf:"bytes,7,opt,name=content,proto3" json:"content,omitempty"`
	Status         MessageStatus          `protobuf:"varint,8,opt,name=status,proto3,enum=api.videoChat.service.v1.MessageStatus" json:"status,omitempty"`
	IsRecalled     bool                   `protobuf:"varint,9,opt,name=is_recalled,json=isRecalled,proto3" json:"is_recalled,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      string                 `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_api_videoChat_service_v1_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_api_videoChat_service_v1_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_api_videoChat_service_v1_message_proto_rawDescGZIP(), []int{1}
}

func (x *Message) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Message) GetConversationId() int64 {
	if x != nil {
		return x.ConversationId
	}
	return 0
}

func (x *Message) GetSenderId() int64 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *Message) GetReceiverId() int64 {
	if x != nil {
		return x.ReceiverId
	}
	return 0
}

func (x *Message) GetConvType() ConversationType {
	if x != nil {
		return x.ConvType
	}
	return ConversationType_SINGLE
}

func (x *Message) GetMsgType() MessageType {
	if x != nil {
		return x.MsgType
	}
	return MessageType_TEXT
}

func (x *Message) GetContent() *MessageContent {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *Message) GetStatus() MessageStatus {
	if x != nil {
		return x.Status
	}
	return MessageStatus_SENDING
}

func (x *Message) GetIsRecalled() bool {
	if x != nil {
		return x.IsRecalled
	}
	return false
}

func (x *Message) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Message) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type Conversation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          ConversationType       `protobuf:"varint,2,opt,name=type,proto3,enum=api.videoChat.service.v1.ConversationType" json:"type,omitempty"`
	TargetId      *int64                 `protobuf:"varint,3,opt,name=target_id,json=targetId,proto3,oneof" json:"target_id,omitempty"` // 单聊对方
	GroupId       *int64                 `protobuf:"varint,4,opt,name=group_id,json=groupId,proto3,oneof" json:"group_id,omitempty"`    // 群聊ID
	Name          string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Avatar        string                 `protobuf:"bytes,6,opt,name=avatar,proto3" json:"avatar,omitempty"`
	LastMessage   string                 `protobuf:"bytes,7,opt,name=last_message,json=lastMessage,proto3" json:"last_message,omitempty"`
	LastMsgType   *MessageType           `protobuf:"varint,8,opt,name=last_msg_type,json=lastMsgType,proto3,enum=api.videoChat.service.v1.MessageType,oneof" json:"last_msg_type,omitempty"`
	LastMsgTime   *int64                 `protobuf:"varint,9,opt,name=last_msg_time,json=lastMsgTime,proto3,oneof" json:"last_msg_time,omitempty"`
	MemberCount   int64                  `protobuf:"varint,10,opt,name=member_count,json=memberCount,proto3" json:"member_count,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Conversation) Reset() {
	*x = Conversation{}
	mi := &file_api_videoChat_service_v1_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Conversation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Conversation) ProtoMessage() {}

func (x *Conversation) ProtoReflect() protoreflect.Message {
	mi := &file_api_videoChat_service_v1_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Conversation.ProtoReflect.Descriptor instead.
func (*Conversation) Descriptor() ([]byte, []int) {
	return file_api_videoChat_service_v1_message_proto_rawDescGZIP(), []int{2}
}

func (x *Conversation) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Conversation) GetType() ConversationType {
	if x != nil {
		return x.Type
	}
	return ConversationType_SINGLE
}

func (x *Conversation) GetTargetId() int64 {
	if x != nil && x.TargetId != nil {
		return *x.TargetId
	}
	return 0
}

func (x *Conversation) GetGroupId() int64 {
	if x != nil && x.GroupId != nil {
		return *x.GroupId
	}
	return 0
}

func (x *Conversation) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Conversation) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *Conversation) GetLastMessage() string {
	if x != nil {
		return x.LastMessage
	}
	return ""
}

func (x *Conversation) GetLastMsgType() MessageType {
	if x != nil && x.LastMsgType != nil {
		return *x.LastMsgType
	}
	return MessageType_TEXT
}

func (x *Conversation) GetLastMsgTime() int64 {
	if x != nil && x.LastMsgTime != nil {
		return *x.LastMsgTime
	}
	return 0
}

func (x *Conversation) GetMemberCount() int64 {
	if x != nil {
		return x.MemberCount
	}
	return 0
}

func (x *Conversation) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Conversation) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type ConversationView struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Conversation  *Conversation          `protobuf:"bytes,1,opt,name=conversation,proto3" json:"conversation,omitempty"`
	UnreadCount   int64                  `protobuf:"varint,2,opt,name=unread_count,json=unreadCount,proto3" json:"unread_count,omitempty"`
	IsPinned      bool                   `protobuf:"varint,3,opt,name=is_pinned,json=isPinned,proto3" json:"is_pinned,omitempty"`
	IsMuted       bool                   `protobuf:"varint,4,opt,name=is_muted,json=isMuted,proto3" json:"is_muted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConversationView) Reset() {
	*x = ConversationView{}
	mi := &file_api_videoChat_service_v1_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConversationView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConversationView) ProtoMessage() {}

func (x *ConversationView) ProtoReflect() protoreflect.Message {
	mi := &file_api_videoChat_service_v1_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConversationView.ProtoReflect.Descriptor instead.
func (*ConversationView) Descriptor() ([]byte, []int) {
	return file_api_videoChat_service_v1_message_proto_rawDescGZIP(), []int{3}
}

func (x *ConversationView) GetConversation() *Conversation {
	if x != nil {
		return x.Conversation
	}
	return nil
}

func (x *ConversationView) GetUnreadCount() int64 {
	if x != nil {
		return x.UnreadCount
	}
	return 0
}

func (x *ConversationView) GetIsPinned() bool {
	if x != nil {
		return x.IsPinned
	}
	return false
}

func (x *ConversationView) GetIsMuted() bool {
	if x != nil {
		return x.IsMuted
	}
	return false
}

// 发送消息
type SendMessageReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SenderId      int64                  `protobuf:"varint,1,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	ReceiverId    int64                  `protobuf:"varint,2,opt,name=receiver_id,json=receiverId,proto3" json:"receiver_id,omitempty"`
	ConvType      ConversationType       `protobuf:"varint,3,opt,name=conv_type,json=convType,proto3,enum=api.videoChat.service.v1.ConversationType" json:"conv_type,omitempty"`
	MsgType       MessageType            `protobuf:"varint,4,opt,name=msg_type,json=msgType,proto3,enum=api.videoChat.service.v1.MessageType" json:"msg_type,omitempty"`
	Content       *MessageContent        `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	ClientMsgId   string                 `protobuf:"bytes,6,opt,name=client_msg_id,json=clientMsgId,proto3" json:"client_msg_id,omitempty"` // 客户端幂等
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageReq) Reset() {
	*x = SendMessageReq{}
	mi := &file_api_videoChat_service_v1_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageReq) ProtoMessage() {}

func (x *SendMessageReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_videoChat_service_v1_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageReq.ProtoReflect.Descriptor instead.
func (*SendMessageReq) Descriptor() ([]byte, []int) {
	return file_api_videoChat_service_v1_message_proto_rawDescGZIP(), []int{4}
}

func (x *SendMessageReq) GetSenderId() int64 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *SendMessageReq) GetReceiverId() int64 {
	if x != nil {
		return x.ReceiverId
	}
	return 0
}

func (x *SendMessageReq) GetConvType() ConversationType {
	if x != nil {
		return x.ConvType
	}
	return ConversationType_SINGLE
}

func (x *SendMessageReq) GetMsgType() MessageType {
	if x != nil {
		return x.MsgType
	}
	return MessageType_TEXT
}

func (x *SendMessageReq) GetContent() *MessageContent {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *SendMessageReq) GetClientMsgId() string {
	if x != nil {
		return x.ClientMsgId
	}
	return ""
}

type SendMessageResp struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MessageId      int64                  `protobuf:"varint,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	ConversationId int64                  `protobuf:"varint,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	Meta           *Metadata              `protobuf:"bytes,3,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SendMessageResp) Reset() {
	*x = SendMessageResp{}
	mi := &file_api_videoChat_service_v1_message_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageResp) ProtoMessage() {}

func (x *SendMessageResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_videoChat_service_v1_message_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageResp.ProtoReflect.Descriptor instead.
func (*SendMessageResp) Descriptor() ([]byte, []int) {
	return file_api_videoChat_service_v1_message_proto_rawDescGZIP(), []int{5}
}

func (x *SendMessageResp) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *SendMessageResp) GetConversationId() int64 {
	if x != nil {
		return x.ConversationId
	}
	return 0
}

func (x *SendMessageResp) GetMeta() *Metadata {
	if x != nil {
		return x.Meta
	}
	return nil
}

// 获取消息列表
type ListMessagesReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ConversationId int64                  `protobuf:"varint,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	LastMsgId      int64                  `protobuf:"varint,3,opt,name=last_msg_id,json=lastMsgId,proto3" json:"last_msg_id,omitempty"`
	Limit          int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListMessagesReq) Reset() {
	*x = ListMessagesReq{}
	mi := &file_api_videoChat_service_v1_message_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMessagesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMessagesReq) ProtoMessage() {}

func (x *ListMessagesReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_videoChat_service_v1_message_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMessagesReq.ProtoReflect.Descriptor instead.
func (*ListMessagesReq) Descriptor() ([]byte, []int) {
	return file_api_videoChat_service_v1_message_proto_rawDescGZIP(), []int{6}
}

func (x *ListMessagesReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListMessagesReq) GetConversationId() int64 {
	if x != nil {
		return x.ConversationId
	}
	return 0
}

func (x *ListMessagesReq) GetLastMsgId() int64 {
	if x != nil {
		return x.LastMsgId
	}
	return 0
}

func (x *ListMessagesReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListMessagesResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*Message             `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	HasMore       bool                   `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	LastMsgId     int64                  `protobuf:"varint,3,opt,name=last_msg_id,json=lastMsgId,proto3" json:"last_msg_id,omitempty"`
	Meta          *Metadata              `protobuf:"bytes,4,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMessagesResp) Reset() {
	*x = ListMessagesResp{}
	mi := &file_api_videoChat_service_v1_message_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMessagesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMessagesResp) ProtoMessage() {}

func (x *ListMessagesResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_videoChat_service_v1_message_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMessagesResp.ProtoReflect.Descriptor instead.
func (*ListMessagesResp) Descriptor() ([]byte, []int) {
	return file_api_videoChat_service_v1_message_proto_rawDescGZIP(), []int{7}
}

func (x *ListMessagesResp) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *ListMessagesResp) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

func (x *ListMessagesResp) GetLastMsgId() int64 {
	if x != nil {
		return x.LastMsgId
	}
	return 0
}

func (x *ListMessagesResp) GetMeta() *Metadata {
	if x != nil {
		return x.Meta
	}
	return nil
}

// 撤回消息
type RecallMessageReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     int64                  `protobuf:"varint,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecallMessageReq) Reset() {
	*x = RecallMessageReq{}
	mi := &file_api_videoChat_service_v1_message_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecallMessageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecallMessageReq) ProtoMessage() {}

func (x *RecallMessageReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_videoChat_service_v1_message_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecallMessageReq.ProtoReflect.Descriptor instead.
func (*RecallMessageReq) Descriptor() ([]byte, []int) {
	return file_api_videoChat_service_v1_message_proto_rawDescGZIP(), []int{8}
}

func (x *RecallMessageReq) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *RecallMessageReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type RecallMessageResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *Metadata              `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecallMessageResp) Reset() {
	*x = RecallMessageResp{}
	mi := &file_api_videoChat_service_v1_message_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecallMessageResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecallMessageResp) ProtoMessage() {}

func (x *RecallMessageResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_videoChat_service_v1_message_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecallMessageResp.ProtoReflect.Descriptor instead.
func (*RecallMessageResp) Descriptor() ([]byte, []int) {
	return file_api_videoChat_service_v1_message_proto_rawDescGZIP(), []int{9}
}

func (x *RecallMessageResp) GetMeta() *Metadata {
	if x != nil {
		return x.Meta
	}
	return nil
}

// 标记已读
type MarkMessagesReadReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ConversationId int64                  `protobuf:"varint,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	LastMsgId      int64                  `protobuf:"varint,3,opt,name=last_msg_id,json=lastMsgId,proto3" json:"last_msg_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MarkMessagesReadReq) Reset() {
	*x = MarkMessagesReadReq{}
	mi := &file_api_videoChat_service_v1_message_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkMessagesReadReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkMessagesReadReq) ProtoMessage() {}

func (x *MarkMessagesReadReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_videoChat_service_v1_message_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkMessagesReadReq.ProtoReflect.Descriptor instead.
func (*MarkMessagesReadReq) Descriptor() ([]byte, []int) {
	return file_api_videoChat_service_v1_message_proto_rawDescGZIP(), []int{10}
}

func (x *MarkMessagesReadReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *MarkMessagesReadReq) GetConversationId() int64 {
	if x != nil {
		return x.ConversationId
	}
	return 0
}

func (x *MarkMessagesReadReq) GetLastMsgId() int64 {
	if x != nil {
		return x.LastMsgId
	}
	return 0
}

type MarkMessagesReadResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *Metadata              `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkMessagesReadResp) Reset() {
	*x = MarkMessagesReadResp{}
	mi := &file_api_videoChat_service_v1_message_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkMessagesReadResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkMessagesReadResp) ProtoMessage() {}

func (x *MarkMessagesReadResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_videoChat_service_v1_message_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkMessagesReadResp.ProtoReflect.Descriptor instead.
func (*MarkMessagesReadResp) Descriptor() ([]byte, []int) {
	return file_api_videoChat_service_v1_message_proto_rawDescGZIP(), []int{11}
}

func (x *MarkMessagesReadResp) GetMeta() *Metadata {
	if x != nil {
		return x.Meta
	}
	return nil
}

// 未读数
type GetUnreadCountReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUnreadCountReq) Reset() {
	*x = GetUnreadCountReq{}
	mi := &file_api_videoChat_service_v1_message_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUnreadCountReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUnreadCountReq) ProtoMessage() {}

func (x *GetUnreadCountReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_videoChat_service_v1_message_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUnreadCountReq.ProtoReflect.Descriptor instead.
func (*GetUnreadCountReq) Descriptor() ([]byte, []int) {
	return file_api_videoChat_service_v1_message_proto_rawDescGZIP(), []int{12}
}

func (x *GetUnreadCountReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetUnreadCountResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalUnread   int64                  `protobuf:"varint,1,opt,name=total_unread,json=totalUnread,proto3" json:"total_unread,omitempty"`
	ConvUnread    map[int64]int64        `protobuf:"bytes,2,rep,name=conv_unread,json=convUnread,proto3" json:"conv_unread,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // conversation_id -> unread
	Meta          *Metadata              `protobuf:"bytes,3,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUnreadCountResp) Reset() {
	*x = GetUnreadCountResp{}
	mi := &file_api_videoChat_service_v1_message_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUnreadCountResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUnreadCountResp) ProtoMessage() {}

func (x *GetUnreadCountResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_videoChat_service_v1_message_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUnreadCountResp.ProtoReflect.Descriptor instead.
func (*GetUnreadCountResp) Descriptor() ([]byte, []int) {
	return file_api_videoChat_service_v1_message_proto_rawDescGZIP(), []int{13}
}

func (x *GetUnreadCountResp) GetTotalUnread() int64 {
	if x != nil {
		return x.TotalUnread
	}
	return 0
}

func (x *GetUnreadCountResp) GetConvUnread() map[int64]int64 {
	if x != nil {
		return x.ConvUnread
	}
	return nil
}

func (x *GetUnreadCountResp) GetMeta() *Metadata {
	if x != nil {
		return x.Meta
	}
	return nil
}

// 会话列表（核心）
type ListConversationsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PageStats     *PageStatsReq          `protobuf:"bytes,2,opt,name=page_stats,json=pageStats,proto3" json:"page_stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConversationsReq) Reset() {
	*x = ListConversationsReq{}
	mi := &file_api_videoChat_service_v1_message_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConversationsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConversationsReq) ProtoMessage() {}

func (x *ListConversationsReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_videoChat_service_v1_message_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConversationsReq.ProtoReflect.Descriptor instead.
func (*ListConversationsReq) Descriptor() ([]byte, []int) {
	return file_api_videoChat_service_v1_message_proto_rawDescGZIP(), []int{14}
}

func (x *ListConversationsReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListConversationsReq) GetPageStats() *PageStatsReq {
	if x != nil {
		return x.PageStats
	}
	return nil
}

type ListConversationsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Conversations []*ConversationView    `protobuf:"bytes,1,rep,name=conversations,proto3" json:"conversations,omitempty"`
	Meta          *Metadata              `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	PageStats     *PageStatsResp         `protobuf:"bytes,3,opt,name=page_stats,json=pageStats,proto3" json:"page_stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConversationsResp) Reset() {
	*x = ListConversationsResp{}
	mi := &file_api_videoChat_service_v1_message_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConversationsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConversationsResp) ProtoMessage() {}

func (x *ListConversationsResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_videoChat_service_v1_message_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConversationsResp.ProtoReflect.Descriptor instead.
func (*ListConversationsResp) Descriptor() ([]byte, []int) {
	return file_api_videoChat_service_v1_message_proto_rawDescGZIP(), []int{15}
}

func (x *ListConversationsResp) GetConversations() []*ConversationView {
	if x != nil {
		return x.Conversations
	}
	return nil
}

func (x *ListConversationsResp) GetMeta() *Metadata {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *ListConversationsResp) GetPageStats() *PageStatsResp {
	if x != nil {
		return x.PageStats
	}
	return nil
}

// 删除会话
type DeleteConversationReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ConversationId int64                  `protobuf:"varint,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeleteConversationReq) Reset() {
	*x = DeleteConversationReq{}
	mi := &file_api_videoChat_service_v1_message_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteConversationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteConversationReq) ProtoMessage() {}

func (x *DeleteConversationReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_videoChat_service_v1_message_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteConversationReq.ProtoReflect.Descriptor instead.
func (*DeleteConversationReq) Descriptor() ([]byte, []int) {
	return file_api_videoChat_service_v1_message_proto_rawDescGZIP(), []int{16}
}

func (x *DeleteConversationReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DeleteConversationReq) GetConversationId() int64 {
	if x != nil {
		return x.ConversationId
	}
	return 0
}

type DeleteConversationResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *Metadata              `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteConversationResp) Reset() {
	*x = DeleteConversationResp{}
	mi := &file_api_videoChat_service_v1_message_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteConversationResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteConversationResp) ProtoMessage() {}

func (x *DeleteConversationResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_videoChat_service_v1_message_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteConversationResp.ProtoReflect.Descriptor instead.
func (*DeleteConversationResp) Descriptor() ([]byte, []int) {
	return file_api_videoChat_service_v1_message_proto_rawDescGZIP(), []int{17}
}

func (x *DeleteConversationResp) GetMeta() *Metadata {
	if x != nil {
		return x.Meta
	}
	return nil
}

// 获取会话
type GetConversationReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TargetId      int64                  `protobuf:"varint,2,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	ConvType      ConversationType       `protobuf:"varint,3,opt,name=conv_type,json=convType,proto3,enum=api.videoChat.service.v1.ConversationType" json:"conv_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConversationReq) Reset() {
	*x = GetConversationReq{}
	mi := &file_api_videoChat_service_v1_message_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConversationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConversationReq) ProtoMessage() {}

func (x *GetConversationReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_videoChat_service_v1_message_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConversationReq.ProtoReflect.Descriptor instead.
func (*GetConversationReq) Descriptor() ([]byte, []int) {
	return file_api_videoChat_service_v1_message_proto_rawDescGZIP(), []int{18}
}

func (x *GetConversationReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetConversationReq) GetTargetId() int64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *GetConversationReq) GetConvType() ConversationType {
	if x != nil {
		return x.ConvType
	}
	return ConversationType_SINGLE
}

type GetConversationResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Conversation  *Conversation          `protobuf:"bytes,1,opt,name=conversation,proto3" json:"conversation,omitempty"`
	Meta          *Metadata              `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConversationResp) Reset() {
	*x = GetConversationResp{}
	mi := &file_api_videoChat_service_v1_message_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConversationResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConversationResp) ProtoMessage() {}

func (x *GetConversationResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_videoChat_service_v1_message_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConversationResp.ProtoReflect.Descriptor instead.
func (*GetConversationResp) Descriptor() ([]byte, []int) {
	return file_api_videoChat_service_v1_message_proto_rawDescGZIP(), []int{19}
}

func (x *GetConversationResp) GetConversation() *Conversation {
	if x != nil {
		return x.Conversation
	}
	return nil
}

func (x *GetConversationResp) GetMeta() *Metadata {
	if x != nil {
		return x.Meta
	}
	return nil
}

// 清空消息
type ClearMessagesReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ConversationId int64                  `protobuf:"varint,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ClearMessagesReq) Reset() {
	*x = ClearMessagesReq{}
	mi := &file_api_videoChat_service_v1_message_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearMessagesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearMessagesReq) ProtoMessage() {}

func (x *ClearMessagesReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_videoChat_service_v1_message_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearMessagesReq.ProtoReflect.Descriptor instead.
func (*ClearMessagesReq) Descriptor() ([]byte, []int) {
	return file_api_videoChat_service_v1_message_proto_rawDescGZIP(), []int{20}
}

func (x *ClearMessagesReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ClearMessagesReq) GetConversationId() int64 {
	if x != nil {
		return x.ConversationId
	}
	return 0
}

type ClearMessagesResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *Metadata              `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearMessagesResp) Reset() {
	*x = ClearMessagesResp{}
	mi := &file_api_videoChat_service_v1_message_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearMessagesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearMessagesResp) ProtoMessage() {}

func (x *ClearMessagesResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_videoChat_service_v1_message_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearMessagesResp.ProtoReflect.Descriptor instead.
func (*ClearMessagesResp) Descriptor() ([]byte, []int) {
	return file_api_videoChat_service_v1_message_proto_rawDescGZIP(), []int{21}
}

func (x *ClearMessagesResp) GetMeta() *Metadata {
	if x != nil {
		return x.Meta
	}
	return nil
}

type UpdateMessageStatusReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     int64                  `protobuf:"varint,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Status        MessageStatus          `protobuf:"varint,2,opt,name=status,proto3,enum=api.videoChat.service.v1.MessageStatus" json:"status,omitempty"`
	OperatorId    int64                  `protobuf:"varint,3,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"` // 操作者ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMessageStatusReq) Reset() {
	*x = UpdateMessageStatusReq{}
	mi := &file_api_videoChat_service_v1_message_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMessageStatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMessageStatusReq) ProtoMessage() {}

func (x *UpdateMessageStatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_videoChat_service_v1_message_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMessageStatusReq.ProtoReflect.Descriptor instead.
func (*UpdateMessageStatusReq) Descriptor() ([]byte, []int) {
	return file_api_videoChat_service_v1_message_proto_rawDescGZIP(), []int{22}
}

func (x *UpdateMessageStatusReq) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *UpdateMessageStatusReq) GetStatus() MessageStatus {
	if x != nil {
		return x.Status
	}
	return MessageStatus_SENDING
}

func (x *UpdateMessageStatusReq) GetOperatorId() int64 {
	if x != nil {
		return x.OperatorId
	}
	return 0
}

type UpdateMessageStatusResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *Metadata              `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMessageStatusResp) Reset() {
	*x = UpdateMessageStatusResp{}
	mi := &file_api_videoChat_service_v1_message_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMessageStatusResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMessageStatusResp) ProtoMessage() {}

func (x *UpdateMessageStatusResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_videoChat_service_v1_message_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMessageStatusResp.ProtoReflect.Descriptor instead.
func (*UpdateMessageStatusResp) Descriptor() ([]byte, []int) {
	return file_api_videoChat_service_v1_message_proto_rawDescGZIP(), []int{23}
}

func (x *UpdateMessageStatusResp) GetMeta() *Metadata {
	if x != nil {
		return x.Meta
	}
	return nil
}

type GetMessageReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     int64                  `protobuf:"varint,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessageReq) Reset() {
	*x = GetMessageReq{}
	mi := &file_api_videoChat_service_v1_message_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessageReq) ProtoMessage() {}

func (x *GetMessageReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_videoChat_service_v1_message_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessageReq.ProtoReflect.Descriptor instead.
func (*GetMessageReq) Descriptor() ([]byte, []int) {
	return file_api_videoChat_service_v1_message_proto_rawDescGZIP(), []int{24}
}

func (x *GetMessageReq) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

type GetMessageResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *Message               `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Meta          *Metadata              `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessageResp) Reset() {
	*x = GetMessageResp{}
	mi := &file_api_videoChat_service_v1_message_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessageResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessageResp) ProtoMessage() {}

func (x *GetMessageResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_videoChat_service_v1_message_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessageResp.ProtoReflect.Descriptor instead.
func (*GetMessageResp) Descriptor() ([]byte, []int) {
	return file_api_videoChat_service_v1_message_proto_rawDescGZIP(), []int{25}
}

func (x *GetMessageResp) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *GetMessageResp) GetMeta() *Metadata {
	if x != nil {
		return x.Meta
	}
	return nil
}

type CreateConversationReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TargetId       int64                  `protobuf:"varint,2,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	ConvType       ConversationType       `protobuf:"varint,3,opt,name=conv_type,json=convType,proto3,enum=api.videoChat.service.v1.ConversationType" json:"conv_type,omitempty"`
	InitialMessage string                 `protobuf:"bytes,4,opt,name=initial_message,json=initialMessage,proto3" json:"initial_message,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateConversationReq) Reset() {
	*x = CreateConversationReq{}
	mi := &file_api_videoChat_service_v1_message_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateConversationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateConversationReq) ProtoMessage() {}

func (x *CreateConversationReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_videoChat_service_v1_message_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateConversationReq.ProtoReflect.Descriptor instead.
func (*CreateConversationReq) Descriptor() ([]byte, []int) {
	return file_api_videoChat_service_v1_message_proto_rawDescGZIP(), []int{26}
}

func (x *CreateConversationReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateConversationReq) GetTargetId() int64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *CreateConversationReq) GetConvType() ConversationType {
	if x != nil {
		return x.ConvType
	}
	return ConversationType_SINGLE
}

func (x *CreateConversationReq) GetInitialMessage() string {
	if x != nil {
		return x.InitialMessage
	}
	return ""
}

type CreateConversationResp struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId int64                  `protobuf:"varint,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	Meta           *Metadata              `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateConversationResp) Reset() {
	*x = CreateConversationResp{}
	mi := &file_api_videoChat_service_v1_message_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateConversationResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateConversationResp) ProtoMessage() {}

func (x *CreateConversationResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_videoChat_service_v1_message_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateConversationResp.ProtoReflect.Descriptor instead.
func (*CreateConversationResp) Descriptor() ([]byte, []int) {
	return file_api_videoChat_service_v1_message_proto_rawDescGZIP(), []int{27}
}

func (x *CreateConversationResp) GetConversationId() int64 {
	if x != nil {
		return x.ConversationId
	}
	return 0
}

func (x *CreateConversationResp) GetMeta() *Metadata {
	if x != nil {
		return x.Meta
	}
	return nil
}

var File_api_videoChat_service_v1_message_proto protoreflect.FileDescriptor

const file_api_videoChat_service_v1_message_proto_rawDesc = "" +
	"\n" +
	"&api/videoChat/service/v1/message.proto\x12\x18api.videoChat.service.v1\x1a#api/videoChat/service/v1/base.proto\"\x99\x03\n" +
	"\x0eMessageContent\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x1b\n" +
	"\timage_url\x18\x02 \x01(\tR\bimageUrl\x12\x1f\n" +
	"\vimage_width\x18\x03 \x01(\x03R\n" +
	"imageWidth\x12!\n" +
	"\fimage_height\x18\x04 \x01(\x03R\vimageHeight\x12\x1b\n" +
	"\tvoice_url\x18\x05 \x01(\tR\bvoiceUrl\x12%\n" +
	"\x0evoice_duration\x18\x06 \x01(\x03R\rvoiceDuration\x12\x1b\n" +
	"\tvideo_url\x18\a \x01(\tR\bvideoUrl\x12\x1f\n" +
	"\vvideo_cover\x18\b \x01(\tR\n" +
	"videoCover\x12%\n" +
	"\x0evideo_duration\x18\t \x01(\x03R\rvideoDuration\x12\x19\n" +
	"\bfile_url\x18\n" +
	" \x01(\tR\afileUrl\x12\x1b\n" +
	"\tfile_name\x18\v \x01(\tR\bfileName\x12\x1b\n" +
	"\tfile_size\x18\f \x01(\x03R\bfileSize\x12\x14\n" +
	"\x05extra\x18\r \x01(\tR\x05extra\"\xef\x03\n" +
	"\aMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\x03R\x0econversationId\x12\x1b\n" +
	"\tsender_id\x18\x03 \x01(\x03R\bsenderId\x12\x1f\n" +
	"\vreceiver_id\x18\x04 \x01(\x03R\n" +
	"receiverId\x12G\n" +
	"\tconv_type\x18\x05 \x01(\x0e2*.api.videoChat.service.v1.ConversationTypeR\bconvType\x12@\n" +
	"\bmsg_type\x18\x06 \x01(\x0e2%.api.videoChat.service.v1.MessageTypeR\amsgType\x12B\n" +
	"\acontent\x18\a \x01(\v2(.api.videoChat.service.v1.MessageContentR\acontent\x12?\n" +
	"\x06status\x18\b \x01(\x0e2'.api.videoChat.service.v1.MessageStatusR\x06status\x12\x1f\n" +
	"\vis_recalled\x18\t \x01(\bR\n" +
	"isRecalled\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\v \x01(\tR\tupdatedAt\"\x88\x04\n" +
	"\fConversation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12>\n" +
	"\x04type\x18\x02 \x01(\x0e2*.api.videoChat.service.v1.ConversationTypeR\x04type\x12 \n" +
	"\ttarget_id\x18\x03 \x01(\x03H\x00R\btargetId\x88\x01\x01\x12\x1e\n" +
	"\bgroup_id\x18\x04 \x01(\x03H\x01R\agroupId\x88\x01\x01\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12\x16\n" +
	"\x06avatar\x18\x06 \x01(\tR\x06avatar\x12!\n" +
	"\flast_message\x18\a \x01(\tR\vlastMessage\x12N\n" +
	"\rlast_msg_type\x18\b \x01(\x0e2%.api.videoChat.service.v1.MessageTypeH\x02R\vlastMsgType\x88\x01\x01\x12'\n" +
	"\rlast_msg_time\x18\t \x01(\x03H\x03R\vlastMsgTime\x88\x01\x01\x12!\n" +
	"\fmember_count\x18\n" +
	" \x01(\x03R\vmemberCount\x12\x1d\n" +
	"\n" +
	"created_at\x18\v \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\f \x01(\tR\tupdatedAtB\f\n" +
	"\n" +
	"_target_idB\v\n" +
	"\t_group_idB\x10\n" +
	"\x0e_last_msg_typeB\x10\n" +
	"\x0e_last_msg_time\"\xb9\x01\n" +
	"\x10ConversationView\x12J\n" +
	"\fconversation\x18\x01 \x01(\v2&.api.videoChat.service.v1.ConversationR\fconversation\x12!\n" +
	"\funread_count\x18\x02 \x01(\x03R\vunreadCount\x12\x1b\n" +
	"\tis_pinned\x18\x03 \x01(\bR\bisPinned\x12\x19\n" +
	"\bis_muted\x18\x04 \x01(\bR\aisMuted\"\xc1\x02\n" +
	"\x0eSendMessageReq\x12\x1b\n" +
	"\tsender_id\x18\x01 \x01(\x03R\bsenderId\x12\x1f\n" +
	"\vreceiver_id\x18\x02 \x01(\x03R\n" +
	"receiverId\x12G\n" +
	"\tconv_type\x18\x03 \x01(\x0e2*.api.videoChat.service.v1.ConversationTypeR\bconvType\x12@\n" +
	"\bmsg_type\x18\x04 \x01(\x0e2%.api.videoChat.service.v1.MessageTypeR\amsgType\x12B\n" +
	"\acontent\x18\x05 \x01(\v2(.api.videoChat.service.v1.MessageContentR\acontent\x12\"\n" +
	"\rclient_msg_id\x18\x06 \x01(\tR\vclientMsgId\"\x91\x01\n" +
	"\x0fSendMessageResp\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\x03R\tmessageId\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\x03R\x0econversationId\x126\n" +
	"\x04meta\x18\x03 \x01(\v2\".api.videoChat.service.v1.MetadataR\x04meta\"\x89\x01\n" +
	"\x0fListMessagesReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\x03R\x0econversationId\x12\x1e\n" +
	"\vlast_msg_id\x18\x03 \x01(\x03R\tlastMsgId\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"\xc4\x01\n" +
	"\x10ListMessagesResp\x12=\n" +
	"\bmessages\x18\x01 \x03(\v2!.api.videoChat.service.v1.MessageR\bmessages\x12\x19\n" +
	"\bhas_more\x18\x02 \x01(\bR\ahasMore\x12\x1e\n" +
	"\vlast_msg_id\x18\x03 \x01(\x03R\tlastMsgId\x126\n" +
	"\x04meta\x18\x04 \x01(\v2\".api.videoChat.service.v1.MetadataR\x04meta\"J\n" +
	"\x10RecallMessageReq\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\x03R\tmessageId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"K\n" +
	"\x11RecallMessageResp\x126\n" +
	"\x04meta\x18\x01 \x01(\v2\".api.videoChat.service.v1.MetadataR\x04meta\"w\n" +
	"\x13MarkMessagesReadReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\x03R\x0econversationId\x12\x1e\n" +
	"\vlast_msg_id\x18\x03 \x01(\x03R\tlastMsgId\"N\n" +
	"\x14MarkMessagesReadResp\x126\n" +
	"\x04meta\x18\x01 \x01(\v2\".api.videoChat.service.v1.MetadataR\x04meta\",\n" +
	"\x11GetUnreadCountReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"\x8d\x02\n" +
	"\x12GetUnreadCountResp\x12!\n" +
	"\ftotal_unread\x18\x01 \x01(\x03R\vtotalUnread\x12]\n" +
	"\vconv_unread\x18\x02 \x03(\v2<.api.videoChat.service.v1.GetUnreadCountResp.ConvUnreadEntryR\n" +
	"convUnread\x126\n" +
	"\x04meta\x18\x03 \x01(\v2\".api.videoChat.service.v1.MetadataR\x04meta\x1a=\n" +
	"\x0fConvUnreadEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x03R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"v\n" +
	"\x14ListConversationsReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12E\n" +
	"\n" +
	"page_stats\x18\x02 \x01(\v2&.api.videoChat.service.v1.PageStatsReqR\tpageStats\"\xe9\x01\n" +
	"\x15ListConversationsResp\x12P\n" +
	"\rconversations\x18\x01 \x03(\v2*.api.videoChat.service.v1.ConversationViewR\rconversations\x126\n" +
	"\x04meta\x18\x02 \x01(\v2\".api.videoChat.service.v1.MetadataR\x04meta\x12F\n" +
	"\n" +
	"page_stats\x18\x03 \x01(\v2'.api.videoChat.service.v1.PageStatsRespR\tpageStats\"Y\n" +
	"\x15DeleteConversationReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\x03R\x0econversationId\"P\n" +
	"\x16DeleteConversationResp\x126\n" +
	"\x04meta\x18\x01 \x01(\v2\".api.videoChat.service.v1.MetadataR\x04meta\"\x93\x01\n" +
	"\x12GetConversationReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1b\n" +
	"\ttarget_id\x18\x02 \x01(\x03R\btargetId\x12G\n" +
	"\tconv_type\x18\x03 \x01(\x0e2*.api.videoChat.service.v1.ConversationTypeR\bconvType\"\x99\x01\n" +
	"\x13GetConversationResp\x12J\n" +
	"\fconversation\x18\x01 \x01(\v2&.api.videoChat.service.v1.ConversationR\fconversation\x126\n" +
	"\x04meta\x18\x02 \x01(\v2\".api.videoChat.service.v1.MetadataR\x04meta\"T\n" +
	"\x10ClearMessagesReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\x03R\x0econversationId\"K\n" +
	"\x11ClearMessagesResp\x126\n" +
	"\x04meta\x18\x01 \x01(\v2\".api.videoChat.service.v1.MetadataR\x04meta\"\x99\x01\n" +
	"\x16UpdateMessageStatusReq\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\x03R\tmessageId\x12?\n" +
	"\x06status\x18\x02 \x01(\x0e2'.api.videoChat.service.v1.MessageStatusR\x06status\x12\x1f\n" +
	"\voperator_id\x18\x03 \x01(\x03R\n" +
	"operatorId\"Q\n" +
	"\x17UpdateMessageStatusResp\x126\n" +
	"\x04meta\x18\x01 \x01(\v2\".api.videoChat.service.v1.MetadataR\x04meta\".\n" +
	"\rGetMessageReq\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\x03R\tmessageId\"\x85\x01\n" +
	"\x0eGetMessageResp\x12;\n" +
	"\amessage\x18\x01 \x01(\v2!.api.videoChat.service.v1.MessageR\amessage\x126\n" +
	"\x04meta\x18\x02 \x01(\v2\".api.videoChat.service.v1.MetadataR\x04meta\"\xbf\x01\n" +
	"\x15CreateConversationReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1b\n" +
	"\ttarget_id\x18\x02 \x01(\x03R\btargetId\x12G\n" +
	"\tconv_type\x18\x03 \x01(\x0e2*.api.videoChat.service.v1.ConversationTypeR\bconvType\x12'\n" +
	"\x0finitial_message\x18\x04 \x01(\tR\x0einitialMessage\"y\n" +
	"\x16CreateConversationResp\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\x03R\x0econversationId\x126\n" +
	"\x04meta\x18\x02 \x01(\v2\".api.videoChat.service.v1.MetadataR\x04meta*)\n" +
	"\x10ConversationType\x12\n" +
	"\n" +
	"\x06SINGLE\x10\x00\x12\t\n" +
	"\x05GROUP\x10\x01*N\n" +
	"\vMessageType\x12\b\n" +
	"\x04TEXT\x10\x00\x12\t\n" +
	"\x05IMAGE\x10\x01\x12\t\n" +
	"\x05VOICE\x10\x02\x12\t\n" +
	"\x05VIDEO\x10\x03\x12\b\n" +
	"\x04FILE\x10\x04\x12\n" +
	"\n" +
	"\x06SYSTEM\x10c*Y\n" +
	"\rMessageStatus\x12\v\n" +
	"\aSENDING\x10\x00\x12\b\n" +
	"\x04SENT\x10\x01\x12\r\n" +
	"\tDELIVERED\x10\x02\x12\b\n" +
	"\x04READ\x10\x03\x12\f\n" +
	"\bRECALLED\x10\x04\x12\n" +
	"\n" +
	"\x06FAILED\x10c2\xc4\n" +
	"\n" +
	"\x0eMessageService\x12b\n" +
	"\vSendMessage\x12(.api.videoChat.service.v1.SendMessageReq\x1a).api.videoChat.service.v1.SendMessageResp\x12e\n" +
	"\fListMessages\x12).api.videoChat.service.v1.ListMessagesReq\x1a*.api.videoChat.service.v1.ListMessagesResp\x12h\n" +
	"\rRecallMessage\x12*.api.videoChat.service.v1.RecallMessageReq\x1a+.api.videoChat.service.v1.RecallMessageResp\x12q\n" +
	"\x10MarkMessagesRead\x12-.api.videoChat.service.v1.MarkMessagesReadReq\x1a..api.videoChat.service.v1.MarkMessagesReadResp\x12k\n" +
	"\x0eGetUnreadCount\x12+.api.videoChat.service.v1.GetUnreadCountReq\x1a,.api.videoChat.service.v1.GetUnreadCountResp\x12t\n" +
	"\x11ListConversations\x12..api.videoChat.service.v1.ListConversationsReq\x1a/.api.videoChat.service.v1.ListConversationsResp\x12w\n" +
	"\x12DeleteConversation\x12/.api.videoChat.service.v1.DeleteConversationReq\x1a0.api.videoChat.service.v1.DeleteConversationResp\x12n\n" +
	"\x0fGetConversation\x12,.api.videoChat.service.v1.GetConversationReq\x1a-.api.videoChat.service.v1.GetConversationResp\x12h\n" +
	"\rClearMessages\x12*.api.videoChat.service.v1.ClearMessagesReq\x1a+.api.videoChat.service.v1.ClearMessagesResp\x12z\n" +
	"\x13UpdateMessageStatus\x120.api.videoChat.service.v1.UpdateMessageStatusReq\x1a1.api.videoChat.service.v1.UpdateMessageStatusResp\x12_\n" +
	"\n" +
	"GetMessage\x12'.api.videoChat.service.v1.GetMessageReq\x1a(.api.videoChat.service.v1.GetMessageResp\x12w\n" +
	"\x12CreateConversation\x12/.api.videoChat.service.v1.CreateConversationReq\x1a0.api.videoChat.service.v1.CreateConversationRespBD\n" +
	"\x18api.videoChat.service.v1P\x01Z&lehu-video/api/videoChat/service/v1;v1b\x06proto3"

var (
	file_api_videoChat_service_v1_message_proto_rawDescOnce sync.Once
	file_api_videoChat_service_v1_message_proto_rawDescData []byte
)

func file_api_videoChat_service_v1_message_proto_rawDescGZIP() []byte {
	file_api_videoChat_service_v1_message_proto_rawDescOnce.Do(func() {
		file_api_videoChat_service_v1_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_videoChat_service_v1_message_proto_rawDesc), len(file_api_videoChat_service_v1_message_proto_rawDesc)))
	})
	return file_api_videoChat_service_v1_message_proto_rawDescData
}

var file_api_videoChat_service_v1_message_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_api_videoChat_service_v1_message_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_api_videoChat_service_v1_message_proto_goTypes = []any{
	(ConversationType)(0),           // 0: api.videoChat.service.v1.ConversationType
	(MessageType)(0),                // 1: api.videoChat.service.v1.MessageType
	(MessageStatus)(0),              // 2: api.videoChat.service.v1.MessageStatus
	(*MessageContent)(nil),          // 3: api.videoChat.service.v1.MessageContent
	(*Message)(nil),                 // 4: api.videoChat.service.v1.Message
	(*Conversation)(nil),            // 5: api.videoChat.service.v1.Conversation
	(*ConversationView)(nil),        // 6: api.videoChat.service.v1.ConversationView
	(*SendMessageReq)(nil),          // 7: api.videoChat.service.v1.SendMessageReq
	(*SendMessageResp)(nil),         // 8: api.videoChat.service.v1.SendMessageResp
	(*ListMessagesReq)(nil),         // 9: api.videoChat.service.v1.ListMessagesReq
	(*ListMessagesResp)(nil),        // 10: api.videoChat.service.v1.ListMessagesResp
	(*RecallMessageReq)(nil),        // 11: api.videoChat.service.v1.RecallMessageReq
	(*RecallMessageResp)(nil),       // 12: api.videoChat.service.v1.RecallMessageResp
	(*MarkMessagesReadReq)(nil),     // 13: api.videoChat.service.v1.MarkMessagesReadReq
	(*MarkMessagesReadResp)(nil),    // 14: api.videoChat.service.v1.MarkMessagesReadResp
	(*GetUnreadCountReq)(nil),       // 15: api.videoChat.service.v1.GetUnreadCountReq
	(*GetUnreadCountResp)(nil),      // 16: api.videoChat.service.v1.GetUnreadCountResp
	(*ListConversationsReq)(nil),    // 17: api.videoChat.service.v1.ListConversationsReq
	(*ListConversationsResp)(nil),   // 18: api.videoChat.service.v1.ListConversationsResp
	(*DeleteConversationReq)(nil),   // 19: api.videoChat.service.v1.DeleteConversationReq
	(*DeleteConversationResp)(nil),  // 20: api.videoChat.service.v1.DeleteConversationResp
	(*GetConversationReq)(nil),      // 21: api.videoChat.service.v1.GetConversationReq
	(*GetConversationResp)(nil),     // 22: api.videoChat.service.v1.GetConversationResp
	(*ClearMessagesReq)(nil),        // 23: api.videoChat.service.v1.ClearMessagesReq
	(*ClearMessagesResp)(nil),       // 24: api.videoChat.service.v1.ClearMessagesResp
	(*UpdateMessageStatusReq)(nil),  // 25: api.videoChat.service.v1.UpdateMessageStatusReq
	(*UpdateMessageStatusResp)(nil), // 26: api.videoChat.service.v1.UpdateMessageStatusResp
	(*GetMessageReq)(nil),           // 27: api.videoChat.service.v1.GetMessageReq
	(*GetMessageResp)(nil),          // 28: api.videoChat.service.v1.GetMessageResp
	(*CreateConversationReq)(nil),   // 29: api.videoChat.service.v1.CreateConversationReq
	(*CreateConversationResp)(nil),  // 30: api.videoChat.service.v1.CreateConversationResp
	nil,                             // 31: api.videoChat.service.v1.GetUnreadCountResp.ConvUnreadEntry
	(*Metadata)(nil),                // 32: api.videoChat.service.v1.Metadata
	(*PageStatsReq)(nil),            // 33: api.videoChat.service.v1.PageStatsReq
	(*PageStatsResp)(nil),           // 34: api.videoChat.service.v1.PageStatsResp
}
var file_api_videoChat_service_v1_message_proto_depIdxs = []int32{
	0,  // 0: api.videoChat.service.v1.Message.conv_type:type_name -> api.videoChat.service.v1.ConversationType
	1,  // 1: api.videoChat.service.v1.Message.msg_type:type_name -> api.videoChat.service.v1.MessageType
	3,  // 2: api.videoChat.service.v1.Message.content:type_name -> api.videoChat.service.v1.MessageContent
	2,  // 3: api.videoChat.service.v1.Message.status:type_name -> api.videoChat.service.v1.MessageStatus
	0,  // 4: api.videoChat.service.v1.Conversation.type:type_name -> api.videoChat.service.v1.ConversationType
	1,  // 5: api.videoChat.service.v1.Conversation.last_msg_type:type_name -> api.videoChat.service.v1.MessageType
	5,  // 6: api.videoChat.service.v1.ConversationView.conversation:type_name -> api.videoChat.service.v1.Conversation
	0,  // 7: api.videoChat.service.v1.SendMessageReq.conv_type:type_name -> api.videoChat.service.v1.ConversationType
	1,  // 8: api.videoChat.service.v1.SendMessageReq.msg_type:type_name -> api.videoChat.service.v1.MessageType
	3,  // 9: api.videoChat.service.v1.SendMessageReq.content:type_name -> api.videoChat.service.v1.MessageContent
	32, // 10: api.videoChat.service.v1.SendMessageResp.meta:type_name -> api.videoChat.service.v1.Metadata
	4,  // 11: api.videoChat.service.v1.ListMessagesResp.messages:type_name -> api.videoChat.service.v1.Message
	32, // 12: api.videoChat.service.v1.ListMessagesResp.meta:type_name -> api.videoChat.service.v1.Metadata
	32, // 13: api.videoChat.service.v1.RecallMessageResp.meta:type_name -> api.videoChat.service.v1.Metadata
	32, // 14: api.videoChat.service.v1.MarkMessagesReadResp.meta:type_name -> api.videoChat.service.v1.Metadata
	31, // 15: api.videoChat.service.v1.GetUnreadCountResp.conv_unread:type_name -> api.videoChat.service.v1.GetUnreadCountResp.ConvUnreadEntry
	32, // 16: api.videoChat.service.v1.GetUnreadCountResp.meta:type_name -> api.videoChat.service.v1.Metadata
	33, // 17: api.videoChat.service.v1.ListConversationsReq.page_stats:type_name -> api.videoChat.service.v1.PageStatsReq
	6,  // 18: api.videoChat.service.v1.ListConversationsResp.conversations:type_name -> api.videoChat.service.v1.ConversationView
	32, // 19: api.videoChat.service.v1.ListConversationsResp.meta:type_name -> api.videoChat.service.v1.Metadata
	34, // 20: api.videoChat.service.v1.ListConversationsResp.page_stats:type_name -> api.videoChat.service.v1.PageStatsResp
	32, // 21: api.videoChat.service.v1.DeleteConversationResp.meta:type_name -> api.videoChat.service.v1.Metadata
	0,  // 22: api.videoChat.service.v1.GetConversationReq.conv_type:type_name -> api.videoChat.service.v1.ConversationType
	5,  // 23: api.videoChat.service.v1.GetConversationResp.conversation:type_name -> api.videoChat.service.v1.Conversation
	32, // 24: api.videoChat.service.v1.GetConversationResp.meta:type_name -> api.videoChat.service.v1.Metadata
	32, // 25: api.videoChat.service.v1.ClearMessagesResp.meta:type_name -> api.videoChat.service.v1.Metadata
	2,  // 26: api.videoChat.service.v1.UpdateMessageStatusReq.status:type_name -> api.videoChat.service.v1.MessageStatus
	32, // 27: api.videoChat.service.v1.UpdateMessageStatusResp.meta:type_name -> api.videoChat.service.v1.Metadata
	4,  // 28: api.videoChat.service.v1.GetMessageResp.message:type_name -> api.videoChat.service.v1.Message
	32, // 29: api.videoChat.service.v1.GetMessageResp.meta:type_name -> api.videoChat.service.v1.Metadata
	0,  // 30: api.videoChat.service.v1.CreateConversationReq.conv_type:type_name -> api.videoChat.service.v1.ConversationType
	32, // 31: api.videoChat.service.v1.CreateConversationResp.meta:type_name -> api.videoChat.service.v1.Metadata
	7,  // 32: api.videoChat.service.v1.MessageService.SendMessage:input_type -> api.videoChat.service.v1.SendMessageReq
	9,  // 33: api.videoChat.service.v1.MessageService.ListMessages:input_type -> api.videoChat.service.v1.ListMessagesReq
	11, // 34: api.videoChat.service.v1.MessageService.RecallMessage:input_type -> api.videoChat.service.v1.RecallMessageReq
	13, // 35: api.videoChat.service.v1.MessageService.MarkMessagesRead:input_type -> api.videoChat.service.v1.MarkMessagesReadReq
	15, // 36: api.videoChat.service.v1.MessageService.GetUnreadCount:input_type -> api.videoChat.service.v1.GetUnreadCountReq
	17, // 37: api.videoChat.service.v1.MessageService.ListConversations:input_type -> api.videoChat.service.v1.ListConversationsReq
	19, // 38: api.videoChat.service.v1.MessageService.DeleteConversation:input_type -> api.videoChat.service.v1.DeleteConversationReq
	21, // 39: api.videoChat.service.v1.MessageService.GetConversation:input_type -> api.videoChat.service.v1.GetConversationReq
	23, // 40: api.videoChat.service.v1.MessageService.ClearMessages:input_type -> api.videoChat.service.v1.ClearMessagesReq
	25, // 41: api.videoChat.service.v1.MessageService.UpdateMessageStatus:input_type -> api.videoChat.service.v1.UpdateMessageStatusReq
	27, // 42: api.videoChat.service.v1.MessageService.GetMessage:input_type -> api.videoChat.service.v1.GetMessageReq
	29, // 43: api.videoChat.service.v1.MessageService.CreateConversation:input_type -> api.videoChat.service.v1.CreateConversationReq
	8,  // 44: api.videoChat.service.v1.MessageService.SendMessage:output_type -> api.videoChat.service.v1.SendMessageResp
	10, // 45: api.videoChat.service.v1.MessageService.ListMessages:output_type -> api.videoChat.service.v1.ListMessagesResp
	12, // 46: api.videoChat.service.v1.MessageService.RecallMessage:output_type -> api.videoChat.service.v1.RecallMessageResp
	14, // 47: api.videoChat.service.v1.MessageService.MarkMessagesRead:output_type -> api.videoChat.service.v1.MarkMessagesReadResp
	16, // 48: api.videoChat.service.v1.MessageService.GetUnreadCount:output_type -> api.videoChat.service.v1.GetUnreadCountResp
	18, // 49: api.videoChat.service.v1.MessageService.ListConversations:output_type -> api.videoChat.service.v1.ListConversationsResp
	20, // 50: api.videoChat.service.v1.MessageService.DeleteConversation:output_type -> api.videoChat.service.v1.DeleteConversationResp
	22, // 51: api.videoChat.service.v1.MessageService.GetConversation:output_type -> api.videoChat.service.v1.GetConversationResp
	24, // 52: api.videoChat.service.v1.MessageService.ClearMessages:output_type -> api.videoChat.service.v1.ClearMessagesResp
	26, // 53: api.videoChat.service.v1.MessageService.UpdateMessageStatus:output_type -> api.videoChat.service.v1.UpdateMessageStatusResp
	28, // 54: api.videoChat.service.v1.MessageService.GetMessage:output_type -> api.videoChat.service.v1.GetMessageResp
	30, // 55: api.videoChat.service.v1.MessageService.CreateConversation:output_type -> api.videoChat.service.v1.CreateConversationResp
	44, // [44:56] is the sub-list for method output_type
	32, // [32:44] is the sub-list for method input_type
	32, // [32:32] is the sub-list for extension type_name
	32, // [32:32] is the sub-list for extension extendee
	0,  // [0:32] is the sub-list for field type_name
}

func init() { file_api_videoChat_service_v1_message_proto_init() }
func file_api_videoChat_service_v1_message_proto_init() {
	if File_api_videoChat_service_v1_message_proto != nil {
		return
	}
	file_api_videoChat_service_v1_base_proto_init()
	file_api_videoChat_service_v1_message_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_videoChat_service_v1_message_proto_rawDesc), len(file_api_videoChat_service_v1_message_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_videoChat_service_v1_message_proto_goTypes,
		DependencyIndexes: file_api_videoChat_service_v1_message_proto_depIdxs,
		EnumInfos:         file_api_videoChat_service_v1_message_proto_enumTypes,
		MessageInfos:      file_api_videoChat_service_v1_message_proto_msgTypes,
	}.Build()
	File_api_videoChat_service_v1_message_proto = out.File
	file_api_videoChat_service_v1_message_proto_goTypes = nil
	file_api_videoChat_service_v1_message_proto_depIdxs = nil
}
