// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"lehu-video/app/videoCore/service/internal/biz"
	"lehu-video/app/videoCore/service/internal/conf"
	"lehu-video/app/videoCore/service/internal/data"
	"lehu-video/app/videoCore/service/internal/server"
	"lehu-video/app/videoCore/service/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, registry *conf.Registry, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	db := data.NewDB(confData, logger)
	client := data.NewRedis(confData)
	dataData, cleanup, err := data.NewData(db, client, logger)
	if err != nil {
		return nil, nil, err
	}
	videoRepo := data.NewVideoRepo(dataData, logger)
	counterRepo := data.NewCounterRepo(client, logger)
	followRepo := data.NewFollowRepo(dataData, logger)
	kafkaProducer := biz.NewKafkaProducer()
	recentViewedManager := biz.NewRecentViewedManager(client)
	feedUsecase := biz.NewFeedUsecase(videoRepo, followRepo, client, kafkaProducer, recentViewedManager, logger)
	videoUsecase := biz.NewVideoUsecase(videoRepo, counterRepo, feedUsecase, recentViewedManager, logger)
	videoServiceService := service.NewVideoServiceService(videoUsecase)
	feedServiceService := service.NewFeedServiceService(feedUsecase)
	userRepo := data.NewUserRepo(dataData, logger)
	userUsecase := biz.NewUserUsecase(userRepo, counterRepo, logger)
	userServiceService := service.NewUserServiceService(userUsecase)
	followUsecase := biz.NewFollowUsecase(followRepo, logger)
	followServiceService := service.NewFollowServiceService(followUsecase)
	favoriteRepo := data.NewFavoriteRepo(dataData, logger)
	favoriteUsecase := biz.NewFavoriteUsecase(favoriteRepo, videoRepo, counterRepo, client, logger)
	favoriteServiceService := service.NewFavoriteServiceService(favoriteUsecase)
	commentRepo := data.NewCommentRepo(dataData, logger)
	cache := data.NewFreeCache(confData)
	hotVideoDetector := biz.NewHotVideoDetector(client, logger)
	commentUsecase := biz.NewCommentUsecase(commentRepo, cache, client, hotVideoDetector, logger)
	commentServiceService := service.NewCommentServiceService(commentUsecase)
	collectionRepo := data.NewCollectionRepo(dataData, logger)
	collectionUsecase := biz.NewCollectionUsecase(collectionRepo, counterRepo, logger)
	collectionServiceService := service.NewCollectionServiceService(collectionUsecase)
	grpcServer := server.NewGRPCServer(confServer, videoServiceService, feedServiceService, userServiceService, followServiceService, favoriteServiceService, commentServiceService, collectionServiceService, logger)
	httpServer := server.NewHTTPServer(confServer, videoServiceService, logger)
	kafkaConsumer := biz.NewKafkaConsumer(confData, feedUsecase, logger)
	kafkaConsumerServer := server.NewKafkaConsumerServer(kafkaConsumer, logger)
	registrar := server.NewRegistrar(registry)
	app := newApp(logger, grpcServer, httpServer, kafkaConsumerServer, registrar)
	return app, func() {
		cleanup()
	}, nil
}
