// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"lehu-video/app/videoCore/service/internal/biz"
	"lehu-video/app/videoCore/service/internal/conf"
	"lehu-video/app/videoCore/service/internal/data"
	"lehu-video/app/videoCore/service/internal/server"
	"lehu-video/app/videoCore/service/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, registry *conf.Registry, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	db := data.NewDB(confData, logger)
	dataData, cleanup, err := data.NewData(db, logger)
	if err != nil {
		return nil, nil, err
	}
	videoRepo := data.NewVideoRepo(dataData, logger)
	videoUsecase := biz.NewVideoUsecase(videoRepo, logger)
	videoServiceService := service.NewVideoServiceService(videoUsecase)
	userRepo := data.NewUserRepo(dataData, logger)
	userUsecase := biz.NewUserUsecase(userRepo, logger)
	userServiceService := service.NewUserServiceService(userUsecase)
	followRepo := data.NewFollowRepo(dataData, logger)
	followUsecase := biz.NewFollowUsecase(followRepo, logger)
	followServiceService := service.NewFollowServiceService(followUsecase)
	favoriteRepo := data.NewFavoriteRepo(dataData, logger)
	favoriteUsecase := biz.NewFavoriteUsecase(favoriteRepo, logger)
	favoriteServiceService := service.NewFavoriteServiceService(favoriteUsecase)
	commentRepo := data.NewCommentRepo(dataData, logger)
	commentUsecase := biz.NewCommentUsecase(commentRepo, logger)
	commentServiceService := service.NewCommentServiceService(commentUsecase)
	collectionRepo := data.NewCollectionRepo(dataData, logger)
	collectionUsecase := biz.NewCollectionUsecase(collectionRepo, logger)
	collectionServiceService := service.NewCollectionServiceService(collectionUsecase)
	grpcServer := server.NewGRPCServer(confServer, videoServiceService, userServiceService, followServiceService, favoriteServiceService, commentServiceService, collectionServiceService, logger)
	httpServer := server.NewHTTPServer(confServer, videoServiceService, logger)
	registrar := server.NewRegistrar(registry)
	app := newApp(logger, grpcServer, httpServer, registrar)
	return app, func() {
		cleanup()
	}, nil
}
