// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"lehu-video/app/videoApi/service/internal/biz"
	"lehu-video/app/videoApi/service/internal/conf"
	"lehu-video/app/videoApi/service/internal/data"
	"lehu-video/app/videoApi/service/internal/pkg/kafka"
	"lehu-video/app/videoApi/service/internal/pkg/websocket"
	"lehu-video/app/videoApi/service/internal/server"
	"lehu-video/app/videoApi/service/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, registry *conf.Registry, confData *conf.Data, auth *conf.Auth, logger log.Logger) (*kratos.App, func(), error) {
	registrar, err := data.NewRegistrar(registry)
	if err != nil {
		return nil, nil, err
	}
	discovery, err := data.NewDiscovery(registry)
	if err != nil {
		return nil, nil, err
	}
	accountServiceClient, err := data.NewAccountServiceClient(discovery)
	if err != nil {
		return nil, nil, err
	}
	authServiceClient, err := data.NewAuthServiceClient(discovery)
	if err != nil {
		return nil, nil, err
	}
	fileServiceClient, err := data.NewFileServiceClient(discovery)
	if err != nil {
		return nil, nil, err
	}
	baseAdapter := data.NewBaseAdapter(accountServiceClient, authServiceClient, fileServiceClient)
	userServiceClient, err := data.NewUserServiceClient(discovery)
	if err != nil {
		return nil, nil, err
	}
	videoServiceClient, err := data.NewVideoServiceClient(discovery)
	if err != nil {
		return nil, nil, err
	}
	feedServiceClient, err := data.NewFeedServiceClient(discovery)
	if err != nil {
		return nil, nil, err
	}
	collectionServiceClient, err := data.NewCollectionServiceClient(discovery)
	if err != nil {
		return nil, nil, err
	}
	commentServiceClient, err := data.NewCommentServiceClient(discovery)
	if err != nil {
		return nil, nil, err
	}
	favoriteServiceClient, err := data.NewFavoriteServiceClient(discovery)
	if err != nil {
		return nil, nil, err
	}
	followServiceClient, err := data.NewFollowServiceClient(discovery)
	if err != nil {
		return nil, nil, err
	}
	coreAdapter := data.NewCoreAdapter(userServiceClient, videoServiceClient, feedServiceClient, collectionServiceClient, commentServiceClient, favoriteServiceClient, followServiceClient, logger)
	groupServiceClient, err := data.NewGroupServiceClient(discovery)
	if err != nil {
		return nil, nil, err
	}
	messageServiceClient, err := data.NewMessageServiceClient(discovery)
	if err != nil {
		return nil, nil, err
	}
	friendServiceClient, err := data.NewFriendServiceClient(discovery)
	if err != nil {
		return nil, nil, err
	}
	chatAdapter := data.NewChatAdapter(groupServiceClient, messageServiceClient, friendServiceClient)
	string2 := biz.NewAuthSecret(auth)
	userUsecase := biz.NewUserUsecase(baseAdapter, coreAdapter, chatAdapter, string2, logger)
	userServiceService := service.NewUserServiceService(userUsecase)
	fileUsecase := biz.NewFileUsecase(baseAdapter, logger)
	fileServiceService := service.NewFileServiceService(fileUsecase)
	videoAssembler := biz.NewVideoAssembler(coreAdapter, logger)
	videoUsecase := biz.NewVideoUsecase(baseAdapter, coreAdapter, videoAssembler, logger)
	videoServiceService := service.NewVideoServiceService(videoUsecase)
	commentUsecase := biz.NewCommentUsecase(coreAdapter, userUsecase, logger)
	commentServiceService := service.NewCommentServiceService(commentUsecase)
	favoriteUsecase := biz.NewFavoriteUsecase(coreAdapter, videoAssembler, logger)
	favoriteServiceService := service.NewFavoriteServiceService(favoriteUsecase)
	followUsecase := biz.NewFollowUsecase(coreAdapter, logger)
	followServiceService := service.NewFollowServiceService(followUsecase)
	collectionUsecase := biz.NewCollectionUsecase(coreAdapter, videoAssembler, logger)
	collectionServiceService := service.NewCollectionServiceService(collectionUsecase, logger)
	groupUsecase := biz.NewGroupUsecase(chatAdapter, logger)
	groupServiceService := service.NewGroupServiceService(groupUsecase, logger)
	messageUsecase := biz.NewMessageUsecase(chatAdapter, logger)
	messageServiceService := service.NewMessageServiceService(messageUsecase, logger)
	friendUsecase := biz.NewFriendUsecase(chatAdapter, coreAdapter, logger)
	friendServiceService := service.NewFriendServiceService(friendUsecase, logger)
	producer := kafka.NewKafkaProducer(confData)
	client, err := data.NewRedis(confData)
	if err != nil {
		return nil, nil, err
	}
	webSocketService := service.NewWebSocketService(messageUsecase, chatAdapter, producer, client, userServiceClient, logger)
	db, err := data.NewDB(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	dataData, cleanup, err := data.NewData(db, client, logger)
	if err != nil {
		return nil, nil, err
	}
	campusRepo := data.NewCampusRepo(dataData, logger)
	campusIDGenerator, err := biz.NewCampusIDGenerator()
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	campusUsecase := biz.NewCampusUsecase(campusRepo, baseAdapter, coreAdapter, campusIDGenerator, string2, logger)
	campusService := service.NewCampusService(campusUsecase, string2)
	httpServer := server.NewHTTPServer(confServer, auth, userServiceService, fileServiceService, videoServiceService, commentServiceService, favoriteServiceService, followServiceService, collectionServiceService, groupServiceService, messageServiceService, friendServiceService, webSocketService, campusService, logger)
	consumer := kafka.NewKafkaConsumer(confData)
	manager := websocket.NewManager(logger, producer, client, chatAdapter, userServiceClient)
	kafkaConsumerService := service.NewKafkaConsumerService(consumer, messageUsecase, manager, client, chatAdapter, logger)
	kafkaConsumerServer := server.NewKafkaConsumerServer(kafkaConsumerService, logger)
	app := newApp(logger, registrar, httpServer, kafkaConsumerServer)
	return app, func() {
		_ = kafkaConsumerService.Close()
		_ = producer.Close()
		_ = client.Close()
		cleanup()
	}, nil
}
