// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.20.3
// source: api/base/service/v1/account.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VoucherType int32

const (
	VoucherType_VOUCHER_PHONE VoucherType = 0
	VoucherType_VOUCHER_EMAIL VoucherType = 1
)

// Enum value maps for VoucherType.
var (
	VoucherType_name = map[int32]string{
		0: "VOUCHER_PHONE",
		1: "VOUCHER_EMAIL",
	}
	VoucherType_value = map[string]int32{
		"VOUCHER_PHONE": 0,
		"VOUCHER_EMAIL": 1,
	}
)

func (x VoucherType) Enum() *VoucherType {
	p := new(VoucherType)
	*p = x
	return p
}

func (x VoucherType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VoucherType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_base_service_v1_account_proto_enumTypes[0].Descriptor()
}

func (VoucherType) Type() protoreflect.EnumType {
	return &file_api_base_service_v1_account_proto_enumTypes[0]
}

func (x VoucherType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VoucherType.Descriptor instead.
func (VoucherType) EnumDescriptor() ([]byte, []int) {
	return file_api_base_service_v1_account_proto_rawDescGZIP(), []int{0}
}

// 手机号和邮箱至少要存在一个
type RegisterReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mobile        string                 `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterReq) Reset() {
	*x = RegisterReq{}
	mi := &file_api_base_service_v1_account_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterReq) ProtoMessage() {}

func (x *RegisterReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_base_service_v1_account_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterReq.ProtoReflect.Descriptor instead.
func (*RegisterReq) Descriptor() ([]byte, []int) {
	return file_api_base_service_v1_account_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterReq) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *RegisterReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type RegisterResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *Metadata              `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	AccountId     int64                  `protobuf:"varint,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"` // 账户id，通过此id绑定跨平台账号
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResp) Reset() {
	*x = RegisterResp{}
	mi := &file_api_base_service_v1_account_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResp) ProtoMessage() {}

func (x *RegisterResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_base_service_v1_account_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResp.ProtoReflect.Descriptor instead.
func (*RegisterResp) Descriptor() ([]byte, []int) {
	return file_api_base_service_v1_account_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResp) GetMeta() *Metadata {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *RegisterResp) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

// 手机号、邮箱、账户id三者至少要存在一个
type CheckAccountReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mobile        string                 `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	AccountId     int64                  `protobuf:"varint,3,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckAccountReq) Reset() {
	*x = CheckAccountReq{}
	mi := &file_api_base_service_v1_account_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckAccountReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAccountReq) ProtoMessage() {}

func (x *CheckAccountReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_base_service_v1_account_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAccountReq.ProtoReflect.Descriptor instead.
func (*CheckAccountReq) Descriptor() ([]byte, []int) {
	return file_api_base_service_v1_account_proto_rawDescGZIP(), []int{2}
}

func (x *CheckAccountReq) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *CheckAccountReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CheckAccountReq) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *CheckAccountReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type CheckAccountResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *Metadata              `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	AccountId     int64                  `protobuf:"varint,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"` // 账户id，通过此id绑定跨平台账号
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckAccountResp) Reset() {
	*x = CheckAccountResp{}
	mi := &file_api_base_service_v1_account_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckAccountResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAccountResp) ProtoMessage() {}

func (x *CheckAccountResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_base_service_v1_account_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAccountResp.ProtoReflect.Descriptor instead.
func (*CheckAccountResp) Descriptor() ([]byte, []int) {
	return file_api_base_service_v1_account_proto_rawDescGZIP(), []int{3}
}

func (x *CheckAccountResp) GetMeta() *Metadata {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *CheckAccountResp) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

type BindReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     int64                  `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	VoucherType   VoucherType            `protobuf:"varint,2,opt,name=voucher_type,json=voucherType,proto3,enum=api.base.service.v1.VoucherType" json:"voucher_type,omitempty"`
	Voucher       string                 `protobuf:"bytes,3,opt,name=voucher,proto3" json:"voucher,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BindReq) Reset() {
	*x = BindReq{}
	mi := &file_api_base_service_v1_account_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindReq) ProtoMessage() {}

func (x *BindReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_base_service_v1_account_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindReq.ProtoReflect.Descriptor instead.
func (*BindReq) Descriptor() ([]byte, []int) {
	return file_api_base_service_v1_account_proto_rawDescGZIP(), []int{4}
}

func (x *BindReq) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *BindReq) GetVoucherType() VoucherType {
	if x != nil {
		return x.VoucherType
	}
	return VoucherType_VOUCHER_PHONE
}

func (x *BindReq) GetVoucher() string {
	if x != nil {
		return x.Voucher
	}
	return ""
}

type BindResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *Metadata              `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BindResp) Reset() {
	*x = BindResp{}
	mi := &file_api_base_service_v1_account_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindResp) ProtoMessage() {}

func (x *BindResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_base_service_v1_account_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindResp.ProtoReflect.Descriptor instead.
func (*BindResp) Descriptor() ([]byte, []int) {
	return file_api_base_service_v1_account_proto_rawDescGZIP(), []int{5}
}

func (x *BindResp) GetMeta() *Metadata {
	if x != nil {
		return x.Meta
	}
	return nil
}

type UnbindReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     int64                  `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	VoucherType   VoucherType            `protobuf:"varint,2,opt,name=voucher_type,json=voucherType,proto3,enum=api.base.service.v1.VoucherType" json:"voucher_type,omitempty"`
	Voucher       string                 `protobuf:"bytes,3,opt,name=voucher,proto3" json:"voucher,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnbindReq) Reset() {
	*x = UnbindReq{}
	mi := &file_api_base_service_v1_account_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnbindReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnbindReq) ProtoMessage() {}

func (x *UnbindReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_base_service_v1_account_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnbindReq.ProtoReflect.Descriptor instead.
func (*UnbindReq) Descriptor() ([]byte, []int) {
	return file_api_base_service_v1_account_proto_rawDescGZIP(), []int{6}
}

func (x *UnbindReq) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *UnbindReq) GetVoucherType() VoucherType {
	if x != nil {
		return x.VoucherType
	}
	return VoucherType_VOUCHER_PHONE
}

func (x *UnbindReq) GetVoucher() string {
	if x != nil {
		return x.Voucher
	}
	return ""
}

type UnbindResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *Metadata              `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnbindResp) Reset() {
	*x = UnbindResp{}
	mi := &file_api_base_service_v1_account_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnbindResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnbindResp) ProtoMessage() {}

func (x *UnbindResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_base_service_v1_account_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnbindResp.ProtoReflect.Descriptor instead.
func (*UnbindResp) Descriptor() ([]byte, []int) {
	return file_api_base_service_v1_account_proto_rawDescGZIP(), []int{7}
}

func (x *UnbindResp) GetMeta() *Metadata {
	if x != nil {
		return x.Meta
	}
	return nil
}

var File_api_base_service_v1_account_proto protoreflect.FileDescriptor

const file_api_base_service_v1_account_proto_rawDesc = "" +
	"\n" +
	"!api/base/service/v1/account.proto\x12\x13api.base.service.v1\x1a\x1eapi/base/service/v1/base.proto\"W\n" +
	"\vRegisterReq\x12\x16\n" +
	"\x06mobile\x18\x01 \x01(\tR\x06mobile\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\"`\n" +
	"\fRegisterResp\x121\n" +
	"\x04meta\x18\x01 \x01(\v2\x1d.api.base.service.v1.MetadataR\x04meta\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\x03R\taccountId\"z\n" +
	"\x0fCheckAccountReq\x12\x16\n" +
	"\x06mobile\x18\x01 \x01(\tR\x06mobile\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"account_id\x18\x03 \x01(\x03R\taccountId\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\"d\n" +
	"\x10CheckAccountResp\x121\n" +
	"\x04meta\x18\x01 \x01(\v2\x1d.api.base.service.v1.MetadataR\x04meta\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\x03R\taccountId\"\x87\x01\n" +
	"\aBindReq\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\x03R\taccountId\x12C\n" +
	"\fvoucher_type\x18\x02 \x01(\x0e2 .api.base.service.v1.VoucherTypeR\vvoucherType\x12\x18\n" +
	"\avoucher\x18\x03 \x01(\tR\avoucher\"=\n" +
	"\bBindResp\x121\n" +
	"\x04meta\x18\x01 \x01(\v2\x1d.api.base.service.v1.MetadataR\x04meta\"\x89\x01\n" +
	"\tUnbindReq\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\x03R\taccountId\x12C\n" +
	"\fvoucher_type\x18\x02 \x01(\x0e2 .api.base.service.v1.VoucherTypeR\vvoucherType\x12\x18\n" +
	"\avoucher\x18\x03 \x01(\tR\avoucher\"?\n" +
	"\n" +
	"UnbindResp\x121\n" +
	"\x04meta\x18\x01 \x01(\v2\x1d.api.base.service.v1.MetadataR\x04meta*3\n" +
	"\vVoucherType\x12\x11\n" +
	"\rVOUCHER_PHONE\x10\x00\x12\x11\n" +
	"\rVOUCHER_EMAIL\x10\x012\xce\x02\n" +
	"\x0eAccountService\x12O\n" +
	"\bRegister\x12 .api.base.service.v1.RegisterReq\x1a!.api.base.service.v1.RegisterResp\x12[\n" +
	"\fCheckAccount\x12$.api.base.service.v1.CheckAccountReq\x1a%.api.base.service.v1.CheckAccountResp\x12C\n" +
	"\x04Bind\x12\x1c.api.base.service.v1.BindReq\x1a\x1d.api.base.service.v1.BindResp\x12I\n" +
	"\x06Unbind\x12\x1e.api.base.service.v1.UnbindReq\x1a\x1f.api.base.service.v1.UnbindRespB:\n" +
	"\x13api.base.service.v1P\x01Z!lehu-video/api/base/service/v1;v1b\x06proto3"

var (
	file_api_base_service_v1_account_proto_rawDescOnce sync.Once
	file_api_base_service_v1_account_proto_rawDescData []byte
)

func file_api_base_service_v1_account_proto_rawDescGZIP() []byte {
	file_api_base_service_v1_account_proto_rawDescOnce.Do(func() {
		file_api_base_service_v1_account_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_base_service_v1_account_proto_rawDesc), len(file_api_base_service_v1_account_proto_rawDesc)))
	})
	return file_api_base_service_v1_account_proto_rawDescData
}

var file_api_base_service_v1_account_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_base_service_v1_account_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_base_service_v1_account_proto_goTypes = []any{
	(VoucherType)(0),         // 0: api.base.service.v1.VoucherType
	(*RegisterReq)(nil),      // 1: api.base.service.v1.RegisterReq
	(*RegisterResp)(nil),     // 2: api.base.service.v1.RegisterResp
	(*CheckAccountReq)(nil),  // 3: api.base.service.v1.CheckAccountReq
	(*CheckAccountResp)(nil), // 4: api.base.service.v1.CheckAccountResp
	(*BindReq)(nil),          // 5: api.base.service.v1.BindReq
	(*BindResp)(nil),         // 6: api.base.service.v1.BindResp
	(*UnbindReq)(nil),        // 7: api.base.service.v1.UnbindReq
	(*UnbindResp)(nil),       // 8: api.base.service.v1.UnbindResp
	(*Metadata)(nil),         // 9: api.base.service.v1.Metadata
}
var file_api_base_service_v1_account_proto_depIdxs = []int32{
	9,  // 0: api.base.service.v1.RegisterResp.meta:type_name -> api.base.service.v1.Metadata
	9,  // 1: api.base.service.v1.CheckAccountResp.meta:type_name -> api.base.service.v1.Metadata
	0,  // 2: api.base.service.v1.BindReq.voucher_type:type_name -> api.base.service.v1.VoucherType
	9,  // 3: api.base.service.v1.BindResp.meta:type_name -> api.base.service.v1.Metadata
	0,  // 4: api.base.service.v1.UnbindReq.voucher_type:type_name -> api.base.service.v1.VoucherType
	9,  // 5: api.base.service.v1.UnbindResp.meta:type_name -> api.base.service.v1.Metadata
	1,  // 6: api.base.service.v1.AccountService.Register:input_type -> api.base.service.v1.RegisterReq
	3,  // 7: api.base.service.v1.AccountService.CheckAccount:input_type -> api.base.service.v1.CheckAccountReq
	5,  // 8: api.base.service.v1.AccountService.Bind:input_type -> api.base.service.v1.BindReq
	7,  // 9: api.base.service.v1.AccountService.Unbind:input_type -> api.base.service.v1.UnbindReq
	2,  // 10: api.base.service.v1.AccountService.Register:output_type -> api.base.service.v1.RegisterResp
	4,  // 11: api.base.service.v1.AccountService.CheckAccount:output_type -> api.base.service.v1.CheckAccountResp
	6,  // 12: api.base.service.v1.AccountService.Bind:output_type -> api.base.service.v1.BindResp
	8,  // 13: api.base.service.v1.AccountService.Unbind:output_type -> api.base.service.v1.UnbindResp
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_api_base_service_v1_account_proto_init() }
func file_api_base_service_v1_account_proto_init() {
	if File_api_base_service_v1_account_proto != nil {
		return
	}
	file_api_base_service_v1_base_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_base_service_v1_account_proto_rawDesc), len(file_api_base_service_v1_account_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_base_service_v1_account_proto_goTypes,
		DependencyIndexes: file_api_base_service_v1_account_proto_depIdxs,
		EnumInfos:         file_api_base_service_v1_account_proto_enumTypes,
		MessageInfos:      file_api_base_service_v1_account_proto_msgTypes,
	}.Build()
	File_api_base_service_v1_account_proto = out.File
	file_api_base_service_v1_account_proto_goTypes = nil
	file_api_base_service_v1_account_proto_depIdxs = nil
}
