// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.20.3
// source: api/videoApi/service/v1/collection.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Collection struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: json:"id,omitempty,string"
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` // 收藏夹id
	// @gotags: json:"userId,omitempty,string"
	UserId        int64  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 用户id
	Name          string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`                    // 收藏夹名称
	Description   string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`      // 收藏夹描述
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Collection) Reset() {
	*x = Collection{}
	mi := &file_api_videoApi_service_v1_collection_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Collection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Collection) ProtoMessage() {}

func (x *Collection) ProtoReflect() protoreflect.Message {
	mi := &file_api_videoApi_service_v1_collection_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Collection.ProtoReflect.Descriptor instead.
func (*Collection) Descriptor() ([]byte, []int) {
	return file_api_videoApi_service_v1_collection_proto_rawDescGZIP(), []int{0}
}

func (x *Collection) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Collection) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Collection) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Collection) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CreateCollectionReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`               // 收藏夹名称
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"` // 收藏夹描述
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCollectionReq) Reset() {
	*x = CreateCollectionReq{}
	mi := &file_api_videoApi_service_v1_collection_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCollectionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCollectionReq) ProtoMessage() {}

func (x *CreateCollectionReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_videoApi_service_v1_collection_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCollectionReq.ProtoReflect.Descriptor instead.
func (*CreateCollectionReq) Descriptor() ([]byte, []int) {
	return file_api_videoApi_service_v1_collection_proto_rawDescGZIP(), []int{1}
}

func (x *CreateCollectionReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateCollectionReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CreateCollectionResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCollectionResp) Reset() {
	*x = CreateCollectionResp{}
	mi := &file_api_videoApi_service_v1_collection_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCollectionResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCollectionResp) ProtoMessage() {}

func (x *CreateCollectionResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_videoApi_service_v1_collection_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCollectionResp.ProtoReflect.Descriptor instead.
func (*CreateCollectionResp) Descriptor() ([]byte, []int) {
	return file_api_videoApi_service_v1_collection_proto_rawDescGZIP(), []int{2}
}

type RemoveCollectionReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: json:"id,omitempty,string"
	Id            int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` // 收藏夹id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveCollectionReq) Reset() {
	*x = RemoveCollectionReq{}
	mi := &file_api_videoApi_service_v1_collection_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveCollectionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveCollectionReq) ProtoMessage() {}

func (x *RemoveCollectionReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_videoApi_service_v1_collection_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveCollectionReq.ProtoReflect.Descriptor instead.
func (*RemoveCollectionReq) Descriptor() ([]byte, []int) {
	return file_api_videoApi_service_v1_collection_proto_rawDescGZIP(), []int{3}
}

func (x *RemoveCollectionReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type RemoveCollectionResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveCollectionResp) Reset() {
	*x = RemoveCollectionResp{}
	mi := &file_api_videoApi_service_v1_collection_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveCollectionResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveCollectionResp) ProtoMessage() {}

func (x *RemoveCollectionResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_videoApi_service_v1_collection_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveCollectionResp.ProtoReflect.Descriptor instead.
func (*RemoveCollectionResp) Descriptor() ([]byte, []int) {
	return file_api_videoApi_service_v1_collection_proto_rawDescGZIP(), []int{4}
}

type ListCollectionReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageStats     *PageStatsReq          `protobuf:"bytes,1,opt,name=page_stats,json=pageStats,proto3" json:"page_stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCollectionReq) Reset() {
	*x = ListCollectionReq{}
	mi := &file_api_videoApi_service_v1_collection_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCollectionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCollectionReq) ProtoMessage() {}

func (x *ListCollectionReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_videoApi_service_v1_collection_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCollectionReq.ProtoReflect.Descriptor instead.
func (*ListCollectionReq) Descriptor() ([]byte, []int) {
	return file_api_videoApi_service_v1_collection_proto_rawDescGZIP(), []int{5}
}

func (x *ListCollectionReq) GetPageStats() *PageStatsReq {
	if x != nil {
		return x.PageStats
	}
	return nil
}

type ListCollectionResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collections   []*Collection          `protobuf:"bytes,1,rep,name=collections,proto3" json:"collections,omitempty"`
	PageStats     *PageStatsResp         `protobuf:"bytes,2,opt,name=page_stats,json=pageStats,proto3" json:"page_stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCollectionResp) Reset() {
	*x = ListCollectionResp{}
	mi := &file_api_videoApi_service_v1_collection_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCollectionResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCollectionResp) ProtoMessage() {}

func (x *ListCollectionResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_videoApi_service_v1_collection_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCollectionResp.ProtoReflect.Descriptor instead.
func (*ListCollectionResp) Descriptor() ([]byte, []int) {
	return file_api_videoApi_service_v1_collection_proto_rawDescGZIP(), []int{6}
}

func (x *ListCollectionResp) GetCollections() []*Collection {
	if x != nil {
		return x.Collections
	}
	return nil
}

func (x *ListCollectionResp) GetPageStats() *PageStatsResp {
	if x != nil {
		return x.PageStats
	}
	return nil
}

type UpdateCollectionReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: json:"id,omitempty,string"
	Id            int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                  // 收藏夹id
	Name          string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`               // 收藏夹名称
	Description   string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"` // 收藏夹描述
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCollectionReq) Reset() {
	*x = UpdateCollectionReq{}
	mi := &file_api_videoApi_service_v1_collection_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCollectionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCollectionReq) ProtoMessage() {}

func (x *UpdateCollectionReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_videoApi_service_v1_collection_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCollectionReq.ProtoReflect.Descriptor instead.
func (*UpdateCollectionReq) Descriptor() ([]byte, []int) {
	return file_api_videoApi_service_v1_collection_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateCollectionReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateCollectionReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateCollectionReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type UpdateCollectionResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCollectionResp) Reset() {
	*x = UpdateCollectionResp{}
	mi := &file_api_videoApi_service_v1_collection_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCollectionResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCollectionResp) ProtoMessage() {}

func (x *UpdateCollectionResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_videoApi_service_v1_collection_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCollectionResp.ProtoReflect.Descriptor instead.
func (*UpdateCollectionResp) Descriptor() ([]byte, []int) {
	return file_api_videoApi_service_v1_collection_proto_rawDescGZIP(), []int{8}
}

type AddVideo2CollectionReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: json:"collectionId,omitempty,string"
	CollectionId int64 `protobuf:"varint,1,opt,name=collection_id,json=collectionId,proto3" json:"collection_id,omitempty"` // 收藏夹id，不传则添加到默认收藏夹
	// @gotags: json:"videoId,omitempty,string"
	VideoId       int64 `protobuf:"varint,2,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"` // 视频id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddVideo2CollectionReq) Reset() {
	*x = AddVideo2CollectionReq{}
	mi := &file_api_videoApi_service_v1_collection_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddVideo2CollectionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddVideo2CollectionReq) ProtoMessage() {}

func (x *AddVideo2CollectionReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_videoApi_service_v1_collection_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddVideo2CollectionReq.ProtoReflect.Descriptor instead.
func (*AddVideo2CollectionReq) Descriptor() ([]byte, []int) {
	return file_api_videoApi_service_v1_collection_proto_rawDescGZIP(), []int{9}
}

func (x *AddVideo2CollectionReq) GetCollectionId() int64 {
	if x != nil {
		return x.CollectionId
	}
	return 0
}

func (x *AddVideo2CollectionReq) GetVideoId() int64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

type AddVideo2CollectionResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddVideo2CollectionResp) Reset() {
	*x = AddVideo2CollectionResp{}
	mi := &file_api_videoApi_service_v1_collection_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddVideo2CollectionResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddVideo2CollectionResp) ProtoMessage() {}

func (x *AddVideo2CollectionResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_videoApi_service_v1_collection_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddVideo2CollectionResp.ProtoReflect.Descriptor instead.
func (*AddVideo2CollectionResp) Descriptor() ([]byte, []int) {
	return file_api_videoApi_service_v1_collection_proto_rawDescGZIP(), []int{10}
}

type RemoveVideoFromCollectionReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: json:"collectionId,omitempty,string"
	CollectionId int64 `protobuf:"varint,1,opt,name=collection_id,json=collectionId,proto3" json:"collection_id,omitempty"` // 收藏夹id
	// @gotags: json:"videoId,omitempty,string"
	VideoId       int64 `protobuf:"varint,2,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"` // 视频id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveVideoFromCollectionReq) Reset() {
	*x = RemoveVideoFromCollectionReq{}
	mi := &file_api_videoApi_service_v1_collection_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveVideoFromCollectionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveVideoFromCollectionReq) ProtoMessage() {}

func (x *RemoveVideoFromCollectionReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_videoApi_service_v1_collection_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveVideoFromCollectionReq.ProtoReflect.Descriptor instead.
func (*RemoveVideoFromCollectionReq) Descriptor() ([]byte, []int) {
	return file_api_videoApi_service_v1_collection_proto_rawDescGZIP(), []int{11}
}

func (x *RemoveVideoFromCollectionReq) GetCollectionId() int64 {
	if x != nil {
		return x.CollectionId
	}
	return 0
}

func (x *RemoveVideoFromCollectionReq) GetVideoId() int64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

type RemoveVideoFromCollectionResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveVideoFromCollectionResp) Reset() {
	*x = RemoveVideoFromCollectionResp{}
	mi := &file_api_videoApi_service_v1_collection_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveVideoFromCollectionResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveVideoFromCollectionResp) ProtoMessage() {}

func (x *RemoveVideoFromCollectionResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_videoApi_service_v1_collection_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveVideoFromCollectionResp.ProtoReflect.Descriptor instead.
func (*RemoveVideoFromCollectionResp) Descriptor() ([]byte, []int) {
	return file_api_videoApi_service_v1_collection_proto_rawDescGZIP(), []int{12}
}

type ListVideo4CollectionReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: json:"collectionId,omitempty,string"
	CollectionId  int64         `protobuf:"varint,1,opt,name=collection_id,json=collectionId,proto3" json:"collection_id,omitempty"` // 收藏夹id
	PageStats     *PageStatsReq `protobuf:"bytes,2,opt,name=page_stats,json=pageStats,proto3" json:"page_stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVideo4CollectionReq) Reset() {
	*x = ListVideo4CollectionReq{}
	mi := &file_api_videoApi_service_v1_collection_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVideo4CollectionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVideo4CollectionReq) ProtoMessage() {}

func (x *ListVideo4CollectionReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_videoApi_service_v1_collection_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVideo4CollectionReq.ProtoReflect.Descriptor instead.
func (*ListVideo4CollectionReq) Descriptor() ([]byte, []int) {
	return file_api_videoApi_service_v1_collection_proto_rawDescGZIP(), []int{13}
}

func (x *ListVideo4CollectionReq) GetCollectionId() int64 {
	if x != nil {
		return x.CollectionId
	}
	return 0
}

func (x *ListVideo4CollectionReq) GetPageStats() *PageStatsReq {
	if x != nil {
		return x.PageStats
	}
	return nil
}

type ListVideo4CollectionResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Videos        []*Video               `protobuf:"bytes,1,rep,name=videos,proto3" json:"videos,omitempty"`
	PageStats     *PageStatsResp         `protobuf:"bytes,2,opt,name=page_stats,json=pageStats,proto3" json:"page_stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVideo4CollectionResp) Reset() {
	*x = ListVideo4CollectionResp{}
	mi := &file_api_videoApi_service_v1_collection_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVideo4CollectionResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVideo4CollectionResp) ProtoMessage() {}

func (x *ListVideo4CollectionResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_videoApi_service_v1_collection_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVideo4CollectionResp.ProtoReflect.Descriptor instead.
func (*ListVideo4CollectionResp) Descriptor() ([]byte, []int) {
	return file_api_videoApi_service_v1_collection_proto_rawDescGZIP(), []int{14}
}

func (x *ListVideo4CollectionResp) GetVideos() []*Video {
	if x != nil {
		return x.Videos
	}
	return nil
}

func (x *ListVideo4CollectionResp) GetPageStats() *PageStatsResp {
	if x != nil {
		return x.PageStats
	}
	return nil
}

var File_api_videoApi_service_v1_collection_proto protoreflect.FileDescriptor

const file_api_videoApi_service_v1_collection_proto_rawDesc = "" +
	"\n" +
	"(api/videoApi/service/v1/collection.proto\x12\x17api.videoApi.service.v1\x1a\x1cgoogle/api/annotations.proto\x1a\"api/videoApi/service/v1/base.proto\x1a#api/videoApi/service/v1/video.proto\"k\n" +
	"\n" +
	"Collection\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\"K\n" +
	"\x13CreateCollectionReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"\x16\n" +
	"\x14CreateCollectionResp\"%\n" +
	"\x13RemoveCollectionReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x16\n" +
	"\x14RemoveCollectionResp\"Y\n" +
	"\x11ListCollectionReq\x12D\n" +
	"\n" +
	"page_stats\x18\x01 \x01(\v2%.api.videoApi.service.v1.PageStatsReqR\tpageStats\"\xa2\x01\n" +
	"\x12ListCollectionResp\x12E\n" +
	"\vcollections\x18\x01 \x03(\v2#.api.videoApi.service.v1.CollectionR\vcollections\x12E\n" +
	"\n" +
	"page_stats\x18\x02 \x01(\v2&.api.videoApi.service.v1.PageStatsRespR\tpageStats\"[\n" +
	"\x13UpdateCollectionReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"\x16\n" +
	"\x14UpdateCollectionResp\"X\n" +
	"\x16AddVideo2CollectionReq\x12#\n" +
	"\rcollection_id\x18\x01 \x01(\x03R\fcollectionId\x12\x19\n" +
	"\bvideo_id\x18\x02 \x01(\x03R\avideoId\"\x19\n" +
	"\x17AddVideo2CollectionResp\"^\n" +
	"\x1cRemoveVideoFromCollectionReq\x12#\n" +
	"\rcollection_id\x18\x01 \x01(\x03R\fcollectionId\x12\x19\n" +
	"\bvideo_id\x18\x02 \x01(\x03R\avideoId\"\x1f\n" +
	"\x1dRemoveVideoFromCollectionResp\"\x84\x01\n" +
	"\x17ListVideo4CollectionReq\x12#\n" +
	"\rcollection_id\x18\x01 \x01(\x03R\fcollectionId\x12D\n" +
	"\n" +
	"page_stats\x18\x02 \x01(\v2%.api.videoApi.service.v1.PageStatsReqR\tpageStats\"\x99\x01\n" +
	"\x18ListVideo4CollectionResp\x126\n" +
	"\x06videos\x18\x01 \x03(\v2\x1e.api.videoApi.service.v1.VideoR\x06videos\x12E\n" +
	"\n" +
	"page_stats\x18\x02 \x01(\v2&.api.videoApi.service.v1.PageStatsRespR\tpageStats2\xce\b\n" +
	"\x11CollectionService\x12\x8a\x01\n" +
	"\x10CreateCollection\x12,.api.videoApi.service.v1.CreateCollectionReq\x1a-.api.videoApi.service.v1.CreateCollectionResp\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/v1/collection\x12\x8c\x01\n" +
	"\x10RemoveCollection\x12,.api.videoApi.service.v1.RemoveCollectionReq\x1a-.api.videoApi.service.v1.RemoveCollectionResp\"\x1b\x82\xd3\xe4\x93\x02\x15*\x13/v1/collection/{id}\x12\x89\x01\n" +
	"\x0eListCollection\x12*.api.videoApi.service.v1.ListCollectionReq\x1a+.api.videoApi.service.v1.ListCollectionResp\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/v1/collection/list\x12\x8a\x01\n" +
	"\x10UpdateCollection\x12,.api.videoApi.service.v1.UpdateCollectionReq\x1a-.api.videoApi.service.v1.UpdateCollectionResp\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\x1a\x0e/v1/collection\x12\x99\x01\n" +
	"\x13AddVideo2Collection\x12/.api.videoApi.service.v1.AddVideo2CollectionReq\x1a0.api.videoApi.service.v1.AddVideo2CollectionResp\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/v1/collection/video\x12\xc3\x01\n" +
	"\x19RemoveVideoFromCollection\x125.api.videoApi.service.v1.RemoveVideoFromCollectionReq\x1a6.api.videoApi.service.v1.RemoveVideoFromCollectionResp\"7\x82\xd3\xe4\x93\x021*//v1/collection/{collection_id}/video/{video_id}\x12\xa1\x01\n" +
	"\x14ListVideo4Collection\x120.api.videoApi.service.v1.ListVideo4CollectionReq\x1a1.api.videoApi.service.v1.ListVideo4CollectionResp\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/v1/collection/video/listBB\n" +
	"\x17api.videoApi.service.v1P\x01Z%lehu-video/api/videoApi/service/v1;v1b\x06proto3"

var (
	file_api_videoApi_service_v1_collection_proto_rawDescOnce sync.Once
	file_api_videoApi_service_v1_collection_proto_rawDescData []byte
)

func file_api_videoApi_service_v1_collection_proto_rawDescGZIP() []byte {
	file_api_videoApi_service_v1_collection_proto_rawDescOnce.Do(func() {
		file_api_videoApi_service_v1_collection_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_videoApi_service_v1_collection_proto_rawDesc), len(file_api_videoApi_service_v1_collection_proto_rawDesc)))
	})
	return file_api_videoApi_service_v1_collection_proto_rawDescData
}

var file_api_videoApi_service_v1_collection_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_api_videoApi_service_v1_collection_proto_goTypes = []any{
	(*Collection)(nil),                    // 0: api.videoApi.service.v1.Collection
	(*CreateCollectionReq)(nil),           // 1: api.videoApi.service.v1.CreateCollectionReq
	(*CreateCollectionResp)(nil),          // 2: api.videoApi.service.v1.CreateCollectionResp
	(*RemoveCollectionReq)(nil),           // 3: api.videoApi.service.v1.RemoveCollectionReq
	(*RemoveCollectionResp)(nil),          // 4: api.videoApi.service.v1.RemoveCollectionResp
	(*ListCollectionReq)(nil),             // 5: api.videoApi.service.v1.ListCollectionReq
	(*ListCollectionResp)(nil),            // 6: api.videoApi.service.v1.ListCollectionResp
	(*UpdateCollectionReq)(nil),           // 7: api.videoApi.service.v1.UpdateCollectionReq
	(*UpdateCollectionResp)(nil),          // 8: api.videoApi.service.v1.UpdateCollectionResp
	(*AddVideo2CollectionReq)(nil),        // 9: api.videoApi.service.v1.AddVideo2CollectionReq
	(*AddVideo2CollectionResp)(nil),       // 10: api.videoApi.service.v1.AddVideo2CollectionResp
	(*RemoveVideoFromCollectionReq)(nil),  // 11: api.videoApi.service.v1.RemoveVideoFromCollectionReq
	(*RemoveVideoFromCollectionResp)(nil), // 12: api.videoApi.service.v1.RemoveVideoFromCollectionResp
	(*ListVideo4CollectionReq)(nil),       // 13: api.videoApi.service.v1.ListVideo4CollectionReq
	(*ListVideo4CollectionResp)(nil),      // 14: api.videoApi.service.v1.ListVideo4CollectionResp
	(*PageStatsReq)(nil),                  // 15: api.videoApi.service.v1.PageStatsReq
	(*PageStatsResp)(nil),                 // 16: api.videoApi.service.v1.PageStatsResp
	(*Video)(nil),                         // 17: api.videoApi.service.v1.Video
}
var file_api_videoApi_service_v1_collection_proto_depIdxs = []int32{
	15, // 0: api.videoApi.service.v1.ListCollectionReq.page_stats:type_name -> api.videoApi.service.v1.PageStatsReq
	0,  // 1: api.videoApi.service.v1.ListCollectionResp.collections:type_name -> api.videoApi.service.v1.Collection
	16, // 2: api.videoApi.service.v1.ListCollectionResp.page_stats:type_name -> api.videoApi.service.v1.PageStatsResp
	15, // 3: api.videoApi.service.v1.ListVideo4CollectionReq.page_stats:type_name -> api.videoApi.service.v1.PageStatsReq
	17, // 4: api.videoApi.service.v1.ListVideo4CollectionResp.videos:type_name -> api.videoApi.service.v1.Video
	16, // 5: api.videoApi.service.v1.ListVideo4CollectionResp.page_stats:type_name -> api.videoApi.service.v1.PageStatsResp
	1,  // 6: api.videoApi.service.v1.CollectionService.CreateCollection:input_type -> api.videoApi.service.v1.CreateCollectionReq
	3,  // 7: api.videoApi.service.v1.CollectionService.RemoveCollection:input_type -> api.videoApi.service.v1.RemoveCollectionReq
	5,  // 8: api.videoApi.service.v1.CollectionService.ListCollection:input_type -> api.videoApi.service.v1.ListCollectionReq
	7,  // 9: api.videoApi.service.v1.CollectionService.UpdateCollection:input_type -> api.videoApi.service.v1.UpdateCollectionReq
	9,  // 10: api.videoApi.service.v1.CollectionService.AddVideo2Collection:input_type -> api.videoApi.service.v1.AddVideo2CollectionReq
	11, // 11: api.videoApi.service.v1.CollectionService.RemoveVideoFromCollection:input_type -> api.videoApi.service.v1.RemoveVideoFromCollectionReq
	13, // 12: api.videoApi.service.v1.CollectionService.ListVideo4Collection:input_type -> api.videoApi.service.v1.ListVideo4CollectionReq
	2,  // 13: api.videoApi.service.v1.CollectionService.CreateCollection:output_type -> api.videoApi.service.v1.CreateCollectionResp
	4,  // 14: api.videoApi.service.v1.CollectionService.RemoveCollection:output_type -> api.videoApi.service.v1.RemoveCollectionResp
	6,  // 15: api.videoApi.service.v1.CollectionService.ListCollection:output_type -> api.videoApi.service.v1.ListCollectionResp
	8,  // 16: api.videoApi.service.v1.CollectionService.UpdateCollection:output_type -> api.videoApi.service.v1.UpdateCollectionResp
	10, // 17: api.videoApi.service.v1.CollectionService.AddVideo2Collection:output_type -> api.videoApi.service.v1.AddVideo2CollectionResp
	12, // 18: api.videoApi.service.v1.CollectionService.RemoveVideoFromCollection:output_type -> api.videoApi.service.v1.RemoveVideoFromCollectionResp
	14, // 19: api.videoApi.service.v1.CollectionService.ListVideo4Collection:output_type -> api.videoApi.service.v1.ListVideo4CollectionResp
	13, // [13:20] is the sub-list for method output_type
	6,  // [6:13] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_api_videoApi_service_v1_collection_proto_init() }
func file_api_videoApi_service_v1_collection_proto_init() {
	if File_api_videoApi_service_v1_collection_proto != nil {
		return
	}
	file_api_videoApi_service_v1_base_proto_init()
	file_api_videoApi_service_v1_video_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_videoApi_service_v1_collection_proto_rawDesc), len(file_api_videoApi_service_v1_collection_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_videoApi_service_v1_collection_proto_goTypes,
		DependencyIndexes: file_api_videoApi_service_v1_collection_proto_depIdxs,
		MessageInfos:      file_api_videoApi_service_v1_collection_proto_msgTypes,
	}.Build()
	File_api_videoApi_service_v1_collection_proto = out.File
	file_api_videoApi_service_v1_collection_proto_goTypes = nil
	file_api_videoApi_service_v1_collection_proto_depIdxs = nil
}
