// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.20.3
// source: api/videoApi/service/v1/follow.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FollowType int32

const (
	FollowType_FOLLOWING FollowType = 0
	FollowType_FOLLOWER  FollowType = 1
	FollowType_BOTH      FollowType = 2
)

// Enum value maps for FollowType.
var (
	FollowType_name = map[int32]string{
		0: "FOLLOWING",
		1: "FOLLOWER",
		2: "BOTH",
	}
	FollowType_value = map[string]int32{
		"FOLLOWING": 0,
		"FOLLOWER":  1,
		"BOTH":      2,
	}
)

func (x FollowType) Enum() *FollowType {
	p := new(FollowType)
	*p = x
	return p
}

func (x FollowType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FollowType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_videoApi_service_v1_follow_proto_enumTypes[0].Descriptor()
}

func (FollowType) Type() protoreflect.EnumType {
	return &file_api_videoApi_service_v1_follow_proto_enumTypes[0]
}

func (x FollowType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FollowType.Descriptor instead.
func (FollowType) EnumDescriptor() ([]byte, []int) {
	return file_api_videoApi_service_v1_follow_proto_rawDescGZIP(), []int{0}
}

type FollowUser struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: json:"id,omitempty,string"
	Id            int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                      // 用户id
	Name          string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                   // 用户名称
	Avatar        string `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`                               // 用户头像
	IsFollowing   bool   `protobuf:"varint,4,opt,name=is_following,json=isFollowing,proto3" json:"is_following,omitempty"` // 当前用户是否关注
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowUser) Reset() {
	*x = FollowUser{}
	mi := &file_api_videoApi_service_v1_follow_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowUser) ProtoMessage() {}

func (x *FollowUser) ProtoReflect() protoreflect.Message {
	mi := &file_api_videoApi_service_v1_follow_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowUser.ProtoReflect.Descriptor instead.
func (*FollowUser) Descriptor() ([]byte, []int) {
	return file_api_videoApi_service_v1_follow_proto_rawDescGZIP(), []int{0}
}

func (x *FollowUser) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FollowUser) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FollowUser) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *FollowUser) GetIsFollowing() bool {
	if x != nil {
		return x.IsFollowing
	}
	return false
}

type AddFollowReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: json:"userId,omitempty,string"
	UserId        int64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 用户id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddFollowReq) Reset() {
	*x = AddFollowReq{}
	mi := &file_api_videoApi_service_v1_follow_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddFollowReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddFollowReq) ProtoMessage() {}

func (x *AddFollowReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_videoApi_service_v1_follow_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddFollowReq.ProtoReflect.Descriptor instead.
func (*AddFollowReq) Descriptor() ([]byte, []int) {
	return file_api_videoApi_service_v1_follow_proto_rawDescGZIP(), []int{1}
}

func (x *AddFollowReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type AddFollowResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddFollowResp) Reset() {
	*x = AddFollowResp{}
	mi := &file_api_videoApi_service_v1_follow_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddFollowResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddFollowResp) ProtoMessage() {}

func (x *AddFollowResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_videoApi_service_v1_follow_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddFollowResp.ProtoReflect.Descriptor instead.
func (*AddFollowResp) Descriptor() ([]byte, []int) {
	return file_api_videoApi_service_v1_follow_proto_rawDescGZIP(), []int{2}
}

type RemoveFollowReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: json:"userId,omitempty,string"
	UserId        int64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 用户id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveFollowReq) Reset() {
	*x = RemoveFollowReq{}
	mi := &file_api_videoApi_service_v1_follow_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveFollowReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFollowReq) ProtoMessage() {}

func (x *RemoveFollowReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_videoApi_service_v1_follow_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFollowReq.ProtoReflect.Descriptor instead.
func (*RemoveFollowReq) Descriptor() ([]byte, []int) {
	return file_api_videoApi_service_v1_follow_proto_rawDescGZIP(), []int{3}
}

func (x *RemoveFollowReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type RemoveFollowResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveFollowResp) Reset() {
	*x = RemoveFollowResp{}
	mi := &file_api_videoApi_service_v1_follow_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveFollowResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFollowResp) ProtoMessage() {}

func (x *RemoveFollowResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_videoApi_service_v1_follow_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFollowResp.ProtoReflect.Descriptor instead.
func (*RemoveFollowResp) Descriptor() ([]byte, []int) {
	return file_api_videoApi_service_v1_follow_proto_rawDescGZIP(), []int{4}
}

type ListFollowingReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: json:"userId,omitempty,string"
	UserId        int64         `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 用户id
	Type          FollowType    `protobuf:"varint,2,opt,name=type,proto3,enum=api.videoApi.service.v1.FollowType" json:"type,omitempty"`
	PageStats     *PageStatsReq `protobuf:"bytes,3,opt,name=page_stats,json=pageStats,proto3" json:"page_stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFollowingReq) Reset() {
	*x = ListFollowingReq{}
	mi := &file_api_videoApi_service_v1_follow_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFollowingReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFollowingReq) ProtoMessage() {}

func (x *ListFollowingReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_videoApi_service_v1_follow_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFollowingReq.ProtoReflect.Descriptor instead.
func (*ListFollowingReq) Descriptor() ([]byte, []int) {
	return file_api_videoApi_service_v1_follow_proto_rawDescGZIP(), []int{5}
}

func (x *ListFollowingReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListFollowingReq) GetType() FollowType {
	if x != nil {
		return x.Type
	}
	return FollowType_FOLLOWING
}

func (x *ListFollowingReq) GetPageStats() *PageStatsReq {
	if x != nil {
		return x.PageStats
	}
	return nil
}

type ListFollowingResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*FollowUser          `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	PageStats     *PageStatsResp         `protobuf:"bytes,2,opt,name=page_stats,json=pageStats,proto3" json:"page_stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFollowingResp) Reset() {
	*x = ListFollowingResp{}
	mi := &file_api_videoApi_service_v1_follow_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFollowingResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFollowingResp) ProtoMessage() {}

func (x *ListFollowingResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_videoApi_service_v1_follow_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFollowingResp.ProtoReflect.Descriptor instead.
func (*ListFollowingResp) Descriptor() ([]byte, []int) {
	return file_api_videoApi_service_v1_follow_proto_rawDescGZIP(), []int{6}
}

func (x *ListFollowingResp) GetUsers() []*FollowUser {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *ListFollowingResp) GetPageStats() *PageStatsResp {
	if x != nil {
		return x.PageStats
	}
	return nil
}

var File_api_videoApi_service_v1_follow_proto protoreflect.FileDescriptor

const file_api_videoApi_service_v1_follow_proto_rawDesc = "" +
	"\n" +
	"$api/videoApi/service/v1/follow.proto\x12\x17api.videoApi.service.v1\x1a\x1cgoogle/api/annotations.proto\x1a\"api/videoApi/service/v1/base.proto\"k\n" +
	"\n" +
	"FollowUser\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\x12!\n" +
	"\fis_following\x18\x04 \x01(\bR\visFollowing\"'\n" +
	"\fAddFollowReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"\x0f\n" +
	"\rAddFollowResp\"*\n" +
	"\x0fRemoveFollowReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"\x12\n" +
	"\x10RemoveFollowResp\"\xaa\x01\n" +
	"\x10ListFollowingReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x127\n" +
	"\x04type\x18\x02 \x01(\x0e2#.api.videoApi.service.v1.FollowTypeR\x04type\x12D\n" +
	"\n" +
	"page_stats\x18\x03 \x01(\v2%.api.videoApi.service.v1.PageStatsReqR\tpageStats\"\x95\x01\n" +
	"\x11ListFollowingResp\x129\n" +
	"\x05users\x18\x01 \x03(\v2#.api.videoApi.service.v1.FollowUserR\x05users\x12E\n" +
	"\n" +
	"page_stats\x18\x02 \x01(\v2&.api.videoApi.service.v1.PageStatsRespR\tpageStats*3\n" +
	"\n" +
	"FollowType\x12\r\n" +
	"\tFOLLOWING\x10\x00\x12\f\n" +
	"\bFOLLOWER\x10\x01\x12\b\n" +
	"\x04BOTH\x10\x022\x8b\x03\n" +
	"\rFollowService\x12q\n" +
	"\tAddFollow\x12%.api.videoApi.service.v1.AddFollowReq\x1a&.api.videoApi.service.v1.AddFollowResp\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*\"\n" +
	"/v1/follow\x12\x81\x01\n" +
	"\fRemoveFollow\x12(.api.videoApi.service.v1.RemoveFollowReq\x1a).api.videoApi.service.v1.RemoveFollowResp\"\x1c\x82\xd3\xe4\x93\x02\x16*\x14/v1/follow/{user_id}\x12\x82\x01\n" +
	"\rListFollowing\x12).api.videoApi.service.v1.ListFollowingReq\x1a*.api.videoApi.service.v1.ListFollowingResp\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/v1/follow/listBB\n" +
	"\x17api.videoApi.service.v1P\x01Z%lehu-video/api/videoApi/service/v1;v1b\x06proto3"

var (
	file_api_videoApi_service_v1_follow_proto_rawDescOnce sync.Once
	file_api_videoApi_service_v1_follow_proto_rawDescData []byte
)

func file_api_videoApi_service_v1_follow_proto_rawDescGZIP() []byte {
	file_api_videoApi_service_v1_follow_proto_rawDescOnce.Do(func() {
		file_api_videoApi_service_v1_follow_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_videoApi_service_v1_follow_proto_rawDesc), len(file_api_videoApi_service_v1_follow_proto_rawDesc)))
	})
	return file_api_videoApi_service_v1_follow_proto_rawDescData
}

var file_api_videoApi_service_v1_follow_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_videoApi_service_v1_follow_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_videoApi_service_v1_follow_proto_goTypes = []any{
	(FollowType)(0),           // 0: api.videoApi.service.v1.FollowType
	(*FollowUser)(nil),        // 1: api.videoApi.service.v1.FollowUser
	(*AddFollowReq)(nil),      // 2: api.videoApi.service.v1.AddFollowReq
	(*AddFollowResp)(nil),     // 3: api.videoApi.service.v1.AddFollowResp
	(*RemoveFollowReq)(nil),   // 4: api.videoApi.service.v1.RemoveFollowReq
	(*RemoveFollowResp)(nil),  // 5: api.videoApi.service.v1.RemoveFollowResp
	(*ListFollowingReq)(nil),  // 6: api.videoApi.service.v1.ListFollowingReq
	(*ListFollowingResp)(nil), // 7: api.videoApi.service.v1.ListFollowingResp
	(*PageStatsReq)(nil),      // 8: api.videoApi.service.v1.PageStatsReq
	(*PageStatsResp)(nil),     // 9: api.videoApi.service.v1.PageStatsResp
}
var file_api_videoApi_service_v1_follow_proto_depIdxs = []int32{
	0, // 0: api.videoApi.service.v1.ListFollowingReq.type:type_name -> api.videoApi.service.v1.FollowType
	8, // 1: api.videoApi.service.v1.ListFollowingReq.page_stats:type_name -> api.videoApi.service.v1.PageStatsReq
	1, // 2: api.videoApi.service.v1.ListFollowingResp.users:type_name -> api.videoApi.service.v1.FollowUser
	9, // 3: api.videoApi.service.v1.ListFollowingResp.page_stats:type_name -> api.videoApi.service.v1.PageStatsResp
	2, // 4: api.videoApi.service.v1.FollowService.AddFollow:input_type -> api.videoApi.service.v1.AddFollowReq
	4, // 5: api.videoApi.service.v1.FollowService.RemoveFollow:input_type -> api.videoApi.service.v1.RemoveFollowReq
	6, // 6: api.videoApi.service.v1.FollowService.ListFollowing:input_type -> api.videoApi.service.v1.ListFollowingReq
	3, // 7: api.videoApi.service.v1.FollowService.AddFollow:output_type -> api.videoApi.service.v1.AddFollowResp
	5, // 8: api.videoApi.service.v1.FollowService.RemoveFollow:output_type -> api.videoApi.service.v1.RemoveFollowResp
	7, // 9: api.videoApi.service.v1.FollowService.ListFollowing:output_type -> api.videoApi.service.v1.ListFollowingResp
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_videoApi_service_v1_follow_proto_init() }
func file_api_videoApi_service_v1_follow_proto_init() {
	if File_api_videoApi_service_v1_follow_proto != nil {
		return
	}
	file_api_videoApi_service_v1_base_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_videoApi_service_v1_follow_proto_rawDesc), len(file_api_videoApi_service_v1_follow_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_videoApi_service_v1_follow_proto_goTypes,
		DependencyIndexes: file_api_videoApi_service_v1_follow_proto_depIdxs,
		EnumInfos:         file_api_videoApi_service_v1_follow_proto_enumTypes,
		MessageInfos:      file_api_videoApi_service_v1_follow_proto_msgTypes,
	}.Build()
	File_api_videoApi_service_v1_follow_proto = out.File
	file_api_videoApi_service_v1_follow_proto_goTypes = nil
	file_api_videoApi_service_v1_follow_proto_depIdxs = nil
}
