// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.8.4
// - protoc             v3.20.3
// source: api/videoApi/service/v1/group.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationGroupServiceApplyJoinGroup = "/api.videoApi.service.v1.GroupService/ApplyJoinGroup"
const OperationGroupServiceCheckGroupAddMode = "/api.videoApi.service.v1.GroupService/CheckGroupAddMode"
const OperationGroupServiceCreateGroup = "/api.videoApi.service.v1.GroupService/CreateGroup"
const OperationGroupServiceDismissGroup = "/api.videoApi.service.v1.GroupService/DismissGroup"
const OperationGroupServiceEnterGroupDirectly = "/api.videoApi.service.v1.GroupService/EnterGroupDirectly"
const OperationGroupServiceGetGroupInfo = "/api.videoApi.service.v1.GroupService/GetGroupInfo"
const OperationGroupServiceGetGroupMembers = "/api.videoApi.service.v1.GroupService/GetGroupMembers"
const OperationGroupServiceHandleGroupApply = "/api.videoApi.service.v1.GroupService/HandleGroupApply"
const OperationGroupServiceLeaveGroup = "/api.videoApi.service.v1.GroupService/LeaveGroup"
const OperationGroupServiceListMyJoinedGroups = "/api.videoApi.service.v1.GroupService/ListMyJoinedGroups"
const OperationGroupServiceLoadMyGroup = "/api.videoApi.service.v1.GroupService/LoadMyGroup"

type GroupServiceHTTPServer interface {
	// ApplyJoinGroup 申请加群
	ApplyJoinGroup(context.Context, *ApplyJoinGroupReq) (*ApplyJoinGroupResp, error)
	// CheckGroupAddMode 检查群聊加群方式
	CheckGroupAddMode(context.Context, *CheckGroupAddModeReq) (*CheckGroupAddModeResp, error)
	// CreateGroup 创建群聊
	CreateGroup(context.Context, *CreateGroupReq) (*CreateGroupResp, error)
	// DismissGroup 解散群聊
	DismissGroup(context.Context, *DismissGroupReq) (*DismissGroupResp, error)
	// EnterGroupDirectly 直接进群
	EnterGroupDirectly(context.Context, *EnterGroupDirectlyReq) (*EnterGroupDirectlyResp, error)
	// GetGroupInfo 获取群聊信息
	GetGroupInfo(context.Context, *GetGroupInfoReq) (*GetGroupInfoResp, error)
	// GetGroupMembers 获取群成员列表
	GetGroupMembers(context.Context, *GetGroupMembersReq) (*GetGroupMembersResp, error)
	// HandleGroupApply 处理加群申请
	HandleGroupApply(context.Context, *HandleGroupApplyReq) (*HandleGroupApplyResp, error)
	// LeaveGroup 退群
	LeaveGroup(context.Context, *LeaveGroupReq) (*LeaveGroupResp, error)
	// ListMyJoinedGroups 获取我加入的群聊
	ListMyJoinedGroups(context.Context, *ListMyJoinedGroupsReq) (*ListMyJoinedGroupsResp, error)
	// LoadMyGroup 获取我创建的群聊
	LoadMyGroup(context.Context, *LoadMyGroupReq) (*LoadMyGroupResp, error)
}

func RegisterGroupServiceHTTPServer(s *http.Server, srv GroupServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/group", _GroupService_CreateGroup0_HTTP_Handler(srv))
	r.POST("/v1/group/my", _GroupService_LoadMyGroup0_HTTP_Handler(srv))
	r.GET("/v1/group/{group_id}/add-mode", _GroupService_CheckGroupAddMode0_HTTP_Handler(srv))
	r.POST("/v1/group/{group_id}/enter", _GroupService_EnterGroupDirectly0_HTTP_Handler(srv))
	r.POST("/v1/group/{group_id}/apply", _GroupService_ApplyJoinGroup0_HTTP_Handler(srv))
	r.DELETE("/v1/group/{group_id}/leave", _GroupService_LeaveGroup0_HTTP_Handler(srv))
	r.DELETE("/v1/group/{group_id}", _GroupService_DismissGroup0_HTTP_Handler(srv))
	r.GET("/v1/group/{group_id}", _GroupService_GetGroupInfo0_HTTP_Handler(srv))
	r.POST("/v1/group/joined", _GroupService_ListMyJoinedGroups0_HTTP_Handler(srv))
	r.POST("/v1/group/apply/handle", _GroupService_HandleGroupApply0_HTTP_Handler(srv))
	r.GET("/v1/group/{group_id}/members", _GroupService_GetGroupMembers0_HTTP_Handler(srv))
}

func _GroupService_CreateGroup0_HTTP_Handler(srv GroupServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateGroupReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationGroupServiceCreateGroup)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateGroup(ctx, req.(*CreateGroupReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateGroupResp)
		return ctx.Result(200, reply)
	}
}

func _GroupService_LoadMyGroup0_HTTP_Handler(srv GroupServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in LoadMyGroupReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationGroupServiceLoadMyGroup)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.LoadMyGroup(ctx, req.(*LoadMyGroupReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*LoadMyGroupResp)
		return ctx.Result(200, reply)
	}
}

func _GroupService_CheckGroupAddMode0_HTTP_Handler(srv GroupServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CheckGroupAddModeReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationGroupServiceCheckGroupAddMode)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CheckGroupAddMode(ctx, req.(*CheckGroupAddModeReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CheckGroupAddModeResp)
		return ctx.Result(200, reply)
	}
}

func _GroupService_EnterGroupDirectly0_HTTP_Handler(srv GroupServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in EnterGroupDirectlyReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationGroupServiceEnterGroupDirectly)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.EnterGroupDirectly(ctx, req.(*EnterGroupDirectlyReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*EnterGroupDirectlyResp)
		return ctx.Result(200, reply)
	}
}

func _GroupService_ApplyJoinGroup0_HTTP_Handler(srv GroupServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ApplyJoinGroupReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationGroupServiceApplyJoinGroup)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ApplyJoinGroup(ctx, req.(*ApplyJoinGroupReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ApplyJoinGroupResp)
		return ctx.Result(200, reply)
	}
}

func _GroupService_LeaveGroup0_HTTP_Handler(srv GroupServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in LeaveGroupReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationGroupServiceLeaveGroup)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.LeaveGroup(ctx, req.(*LeaveGroupReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*LeaveGroupResp)
		return ctx.Result(200, reply)
	}
}

func _GroupService_DismissGroup0_HTTP_Handler(srv GroupServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DismissGroupReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationGroupServiceDismissGroup)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DismissGroup(ctx, req.(*DismissGroupReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DismissGroupResp)
		return ctx.Result(200, reply)
	}
}

func _GroupService_GetGroupInfo0_HTTP_Handler(srv GroupServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetGroupInfoReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationGroupServiceGetGroupInfo)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetGroupInfo(ctx, req.(*GetGroupInfoReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetGroupInfoResp)
		return ctx.Result(200, reply)
	}
}

func _GroupService_ListMyJoinedGroups0_HTTP_Handler(srv GroupServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListMyJoinedGroupsReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationGroupServiceListMyJoinedGroups)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListMyJoinedGroups(ctx, req.(*ListMyJoinedGroupsReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListMyJoinedGroupsResp)
		return ctx.Result(200, reply)
	}
}

func _GroupService_HandleGroupApply0_HTTP_Handler(srv GroupServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in HandleGroupApplyReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationGroupServiceHandleGroupApply)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.HandleGroupApply(ctx, req.(*HandleGroupApplyReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*HandleGroupApplyResp)
		return ctx.Result(200, reply)
	}
}

func _GroupService_GetGroupMembers0_HTTP_Handler(srv GroupServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetGroupMembersReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationGroupServiceGetGroupMembers)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetGroupMembers(ctx, req.(*GetGroupMembersReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetGroupMembersResp)
		return ctx.Result(200, reply)
	}
}

type GroupServiceHTTPClient interface {
	ApplyJoinGroup(ctx context.Context, req *ApplyJoinGroupReq, opts ...http.CallOption) (rsp *ApplyJoinGroupResp, err error)
	CheckGroupAddMode(ctx context.Context, req *CheckGroupAddModeReq, opts ...http.CallOption) (rsp *CheckGroupAddModeResp, err error)
	CreateGroup(ctx context.Context, req *CreateGroupReq, opts ...http.CallOption) (rsp *CreateGroupResp, err error)
	DismissGroup(ctx context.Context, req *DismissGroupReq, opts ...http.CallOption) (rsp *DismissGroupResp, err error)
	EnterGroupDirectly(ctx context.Context, req *EnterGroupDirectlyReq, opts ...http.CallOption) (rsp *EnterGroupDirectlyResp, err error)
	GetGroupInfo(ctx context.Context, req *GetGroupInfoReq, opts ...http.CallOption) (rsp *GetGroupInfoResp, err error)
	GetGroupMembers(ctx context.Context, req *GetGroupMembersReq, opts ...http.CallOption) (rsp *GetGroupMembersResp, err error)
	HandleGroupApply(ctx context.Context, req *HandleGroupApplyReq, opts ...http.CallOption) (rsp *HandleGroupApplyResp, err error)
	LeaveGroup(ctx context.Context, req *LeaveGroupReq, opts ...http.CallOption) (rsp *LeaveGroupResp, err error)
	ListMyJoinedGroups(ctx context.Context, req *ListMyJoinedGroupsReq, opts ...http.CallOption) (rsp *ListMyJoinedGroupsResp, err error)
	LoadMyGroup(ctx context.Context, req *LoadMyGroupReq, opts ...http.CallOption) (rsp *LoadMyGroupResp, err error)
}

type GroupServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewGroupServiceHTTPClient(client *http.Client) GroupServiceHTTPClient {
	return &GroupServiceHTTPClientImpl{client}
}

func (c *GroupServiceHTTPClientImpl) ApplyJoinGroup(ctx context.Context, in *ApplyJoinGroupReq, opts ...http.CallOption) (*ApplyJoinGroupResp, error) {
	var out ApplyJoinGroupResp
	pattern := "/v1/group/{group_id}/apply"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationGroupServiceApplyJoinGroup))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *GroupServiceHTTPClientImpl) CheckGroupAddMode(ctx context.Context, in *CheckGroupAddModeReq, opts ...http.CallOption) (*CheckGroupAddModeResp, error) {
	var out CheckGroupAddModeResp
	pattern := "/v1/group/{group_id}/add-mode"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationGroupServiceCheckGroupAddMode))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *GroupServiceHTTPClientImpl) CreateGroup(ctx context.Context, in *CreateGroupReq, opts ...http.CallOption) (*CreateGroupResp, error) {
	var out CreateGroupResp
	pattern := "/v1/group"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationGroupServiceCreateGroup))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *GroupServiceHTTPClientImpl) DismissGroup(ctx context.Context, in *DismissGroupReq, opts ...http.CallOption) (*DismissGroupResp, error) {
	var out DismissGroupResp
	pattern := "/v1/group/{group_id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationGroupServiceDismissGroup))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *GroupServiceHTTPClientImpl) EnterGroupDirectly(ctx context.Context, in *EnterGroupDirectlyReq, opts ...http.CallOption) (*EnterGroupDirectlyResp, error) {
	var out EnterGroupDirectlyResp
	pattern := "/v1/group/{group_id}/enter"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationGroupServiceEnterGroupDirectly))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *GroupServiceHTTPClientImpl) GetGroupInfo(ctx context.Context, in *GetGroupInfoReq, opts ...http.CallOption) (*GetGroupInfoResp, error) {
	var out GetGroupInfoResp
	pattern := "/v1/group/{group_id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationGroupServiceGetGroupInfo))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *GroupServiceHTTPClientImpl) GetGroupMembers(ctx context.Context, in *GetGroupMembersReq, opts ...http.CallOption) (*GetGroupMembersResp, error) {
	var out GetGroupMembersResp
	pattern := "/v1/group/{group_id}/members"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationGroupServiceGetGroupMembers))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *GroupServiceHTTPClientImpl) HandleGroupApply(ctx context.Context, in *HandleGroupApplyReq, opts ...http.CallOption) (*HandleGroupApplyResp, error) {
	var out HandleGroupApplyResp
	pattern := "/v1/group/apply/handle"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationGroupServiceHandleGroupApply))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *GroupServiceHTTPClientImpl) LeaveGroup(ctx context.Context, in *LeaveGroupReq, opts ...http.CallOption) (*LeaveGroupResp, error) {
	var out LeaveGroupResp
	pattern := "/v1/group/{group_id}/leave"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationGroupServiceLeaveGroup))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *GroupServiceHTTPClientImpl) ListMyJoinedGroups(ctx context.Context, in *ListMyJoinedGroupsReq, opts ...http.CallOption) (*ListMyJoinedGroupsResp, error) {
	var out ListMyJoinedGroupsResp
	pattern := "/v1/group/joined"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationGroupServiceListMyJoinedGroups))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *GroupServiceHTTPClientImpl) LoadMyGroup(ctx context.Context, in *LoadMyGroupReq, opts ...http.CallOption) (*LoadMyGroupResp, error) {
	var out LoadMyGroupResp
	pattern := "/v1/group/my"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationGroupServiceLoadMyGroup))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
