// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.20.3
// source: api/videoApi/service/v1/video.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VideoService_PreSign4UploadVideo_FullMethodName     = "/api.videoApi.service.v1.VideoService/PreSign4UploadVideo"
	VideoService_PreSign4UploadCover_FullMethodName     = "/api.videoApi.service.v1.VideoService/PreSign4UploadCover"
	VideoService_ReportFinishUpload_FullMethodName      = "/api.videoApi.service.v1.VideoService/ReportFinishUpload"
	VideoService_ReportVideoFinishUpload_FullMethodName = "/api.videoApi.service.v1.VideoService/ReportVideoFinishUpload"
	VideoService_FeedShortVideo_FullMethodName          = "/api.videoApi.service.v1.VideoService/FeedShortVideo"
	VideoService_GetVideoById_FullMethodName            = "/api.videoApi.service.v1.VideoService/GetVideoById"
	VideoService_ListPublishedVideo_FullMethodName      = "/api.videoApi.service.v1.VideoService/ListPublishedVideo"
)

// VideoServiceClient is the client API for VideoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VideoServiceClient interface {
	// 预注册上传视频
	PreSign4UploadVideo(ctx context.Context, in *PreSign4UploadVideoReq, opts ...grpc.CallOption) (*PreSign4UploadVideoResp, error)
	// 预注册上传封面
	PreSign4UploadCover(ctx context.Context, in *PreSign4UploadCoverReq, opts ...grpc.CallOption) (*PreSign4UploadCoverResp, error)
	// 通用确认上传完成
	ReportFinishUpload(ctx context.Context, in *ReportFinishUploadReq, opts ...grpc.CallOption) (*ReportFinishUploadResp, error)
	// 确认视频上传完成
	ReportVideoFinishUpload(ctx context.Context, in *ReportVideoFinishUploadReq, opts ...grpc.CallOption) (*ReportVideoFinishUploadResp, error)
	// 刷视频
	FeedShortVideo(ctx context.Context, in *FeedShortVideoReq, opts ...grpc.CallOption) (*FeedShortVideoResp, error)
	// 获取视频信息
	GetVideoById(ctx context.Context, in *GetVideoByIdReq, opts ...grpc.CallOption) (*GetVideoByIdResp, error)
	// 获取当前用户的发布视频列表
	ListPublishedVideo(ctx context.Context, in *ListPublishedVideoReq, opts ...grpc.CallOption) (*ListPublishedVideoResp, error)
}

type videoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVideoServiceClient(cc grpc.ClientConnInterface) VideoServiceClient {
	return &videoServiceClient{cc}
}

func (c *videoServiceClient) PreSign4UploadVideo(ctx context.Context, in *PreSign4UploadVideoReq, opts ...grpc.CallOption) (*PreSign4UploadVideoResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PreSign4UploadVideoResp)
	err := c.cc.Invoke(ctx, VideoService_PreSign4UploadVideo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoServiceClient) PreSign4UploadCover(ctx context.Context, in *PreSign4UploadCoverReq, opts ...grpc.CallOption) (*PreSign4UploadCoverResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PreSign4UploadCoverResp)
	err := c.cc.Invoke(ctx, VideoService_PreSign4UploadCover_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoServiceClient) ReportFinishUpload(ctx context.Context, in *ReportFinishUploadReq, opts ...grpc.CallOption) (*ReportFinishUploadResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportFinishUploadResp)
	err := c.cc.Invoke(ctx, VideoService_ReportFinishUpload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoServiceClient) ReportVideoFinishUpload(ctx context.Context, in *ReportVideoFinishUploadReq, opts ...grpc.CallOption) (*ReportVideoFinishUploadResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportVideoFinishUploadResp)
	err := c.cc.Invoke(ctx, VideoService_ReportVideoFinishUpload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoServiceClient) FeedShortVideo(ctx context.Context, in *FeedShortVideoReq, opts ...grpc.CallOption) (*FeedShortVideoResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FeedShortVideoResp)
	err := c.cc.Invoke(ctx, VideoService_FeedShortVideo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoServiceClient) GetVideoById(ctx context.Context, in *GetVideoByIdReq, opts ...grpc.CallOption) (*GetVideoByIdResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetVideoByIdResp)
	err := c.cc.Invoke(ctx, VideoService_GetVideoById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoServiceClient) ListPublishedVideo(ctx context.Context, in *ListPublishedVideoReq, opts ...grpc.CallOption) (*ListPublishedVideoResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPublishedVideoResp)
	err := c.cc.Invoke(ctx, VideoService_ListPublishedVideo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VideoServiceServer is the server API for VideoService service.
// All implementations must embed UnimplementedVideoServiceServer
// for forward compatibility.
type VideoServiceServer interface {
	// 预注册上传视频
	PreSign4UploadVideo(context.Context, *PreSign4UploadVideoReq) (*PreSign4UploadVideoResp, error)
	// 预注册上传封面
	PreSign4UploadCover(context.Context, *PreSign4UploadCoverReq) (*PreSign4UploadCoverResp, error)
	// 通用确认上传完成
	ReportFinishUpload(context.Context, *ReportFinishUploadReq) (*ReportFinishUploadResp, error)
	// 确认视频上传完成
	ReportVideoFinishUpload(context.Context, *ReportVideoFinishUploadReq) (*ReportVideoFinishUploadResp, error)
	// 刷视频
	FeedShortVideo(context.Context, *FeedShortVideoReq) (*FeedShortVideoResp, error)
	// 获取视频信息
	GetVideoById(context.Context, *GetVideoByIdReq) (*GetVideoByIdResp, error)
	// 获取当前用户的发布视频列表
	ListPublishedVideo(context.Context, *ListPublishedVideoReq) (*ListPublishedVideoResp, error)
	mustEmbedUnimplementedVideoServiceServer()
}

// UnimplementedVideoServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVideoServiceServer struct{}

func (UnimplementedVideoServiceServer) PreSign4UploadVideo(context.Context, *PreSign4UploadVideoReq) (*PreSign4UploadVideoResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PreSign4UploadVideo not implemented")
}
func (UnimplementedVideoServiceServer) PreSign4UploadCover(context.Context, *PreSign4UploadCoverReq) (*PreSign4UploadCoverResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PreSign4UploadCover not implemented")
}
func (UnimplementedVideoServiceServer) ReportFinishUpload(context.Context, *ReportFinishUploadReq) (*ReportFinishUploadResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportFinishUpload not implemented")
}
func (UnimplementedVideoServiceServer) ReportVideoFinishUpload(context.Context, *ReportVideoFinishUploadReq) (*ReportVideoFinishUploadResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportVideoFinishUpload not implemented")
}
func (UnimplementedVideoServiceServer) FeedShortVideo(context.Context, *FeedShortVideoReq) (*FeedShortVideoResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FeedShortVideo not implemented")
}
func (UnimplementedVideoServiceServer) GetVideoById(context.Context, *GetVideoByIdReq) (*GetVideoByIdResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVideoById not implemented")
}
func (UnimplementedVideoServiceServer) ListPublishedVideo(context.Context, *ListPublishedVideoReq) (*ListPublishedVideoResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPublishedVideo not implemented")
}
func (UnimplementedVideoServiceServer) mustEmbedUnimplementedVideoServiceServer() {}
func (UnimplementedVideoServiceServer) testEmbeddedByValue()                      {}

// UnsafeVideoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VideoServiceServer will
// result in compilation errors.
type UnsafeVideoServiceServer interface {
	mustEmbedUnimplementedVideoServiceServer()
}

func RegisterVideoServiceServer(s grpc.ServiceRegistrar, srv VideoServiceServer) {
	// If the following call pancis, it indicates UnimplementedVideoServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VideoService_ServiceDesc, srv)
}

func _VideoService_PreSign4UploadVideo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PreSign4UploadVideoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServiceServer).PreSign4UploadVideo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VideoService_PreSign4UploadVideo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServiceServer).PreSign4UploadVideo(ctx, req.(*PreSign4UploadVideoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _VideoService_PreSign4UploadCover_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PreSign4UploadCoverReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServiceServer).PreSign4UploadCover(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VideoService_PreSign4UploadCover_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServiceServer).PreSign4UploadCover(ctx, req.(*PreSign4UploadCoverReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _VideoService_ReportFinishUpload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportFinishUploadReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServiceServer).ReportFinishUpload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VideoService_ReportFinishUpload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServiceServer).ReportFinishUpload(ctx, req.(*ReportFinishUploadReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _VideoService_ReportVideoFinishUpload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportVideoFinishUploadReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServiceServer).ReportVideoFinishUpload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VideoService_ReportVideoFinishUpload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServiceServer).ReportVideoFinishUpload(ctx, req.(*ReportVideoFinishUploadReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _VideoService_FeedShortVideo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FeedShortVideoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServiceServer).FeedShortVideo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VideoService_FeedShortVideo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServiceServer).FeedShortVideo(ctx, req.(*FeedShortVideoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _VideoService_GetVideoById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVideoByIdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServiceServer).GetVideoById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VideoService_GetVideoById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServiceServer).GetVideoById(ctx, req.(*GetVideoByIdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _VideoService_ListPublishedVideo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPublishedVideoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServiceServer).ListPublishedVideo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VideoService_ListPublishedVideo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServiceServer).ListPublishedVideo(ctx, req.(*ListPublishedVideoReq))
	}
	return interceptor(ctx, in, info, handler)
}

// VideoService_ServiceDesc is the grpc.ServiceDesc for VideoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VideoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.videoApi.service.v1.VideoService",
	HandlerType: (*VideoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PreSign4UploadVideo",
			Handler:    _VideoService_PreSign4UploadVideo_Handler,
		},
		{
			MethodName: "PreSign4UploadCover",
			Handler:    _VideoService_PreSign4UploadCover_Handler,
		},
		{
			MethodName: "ReportFinishUpload",
			Handler:    _VideoService_ReportFinishUpload_Handler,
		},
		{
			MethodName: "ReportVideoFinishUpload",
			Handler:    _VideoService_ReportVideoFinishUpload_Handler,
		},
		{
			MethodName: "FeedShortVideo",
			Handler:    _VideoService_FeedShortVideo_Handler,
		},
		{
			MethodName: "GetVideoById",
			Handler:    _VideoService_GetVideoById_Handler,
		},
		{
			MethodName: "ListPublishedVideo",
			Handler:    _VideoService_ListPublishedVideo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/videoApi/service/v1/video.proto",
}
