// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"lehu-video/app/videoChat/service/internal/biz"
	"lehu-video/app/videoChat/service/internal/conf"
	"lehu-video/app/videoChat/service/internal/data"
	"lehu-video/app/videoChat/service/internal/server"
	"lehu-video/app/videoChat/service/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, idgen *conf.Idgen, registry *conf.Registry, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	db := data.NewDB(confData, logger)
	discovery := data.NewDiscovery(registry)
	userServiceClient := data.NewUserServiceClient(discovery)
	client := data.NewRedisClient(confData)
	dataData, cleanup, err := data.NewData(db, userServiceClient, client, logger)
	if err != nil {
		return nil, nil, err
	}
	groupRepo := data.NewGroupRepo(dataData, logger)
	generator := data.NewIdGenerator(idgen)
	conversationRepo := data.NewConversationRepo(dataData, generator, logger)
	groupUsecase := biz.NewGroupUsecase(groupRepo, conversationRepo, generator, logger)
	groupServiceService := service.NewGroupServiceService(groupUsecase, logger)
	messageRepo := data.NewMessageRepo(dataData, logger)
	friendRepo := data.NewFriendRepo(dataData, userServiceClient, client, logger)
	messageUsecase := biz.NewMessageUsecase(messageRepo, friendRepo, groupRepo, conversationRepo, generator, logger)
	messageServiceService := service.NewMessageServiceService(messageUsecase, logger)
	friendUsecase := biz.NewFriendUsecase(friendRepo, generator, logger)
	friendServiceService := service.NewFriendServiceService(friendUsecase)
	grpcServer := server.NewGRPCServer(confServer, groupServiceService, messageServiceService, friendServiceService, logger)
	registrar := server.NewRegistrar(registry)
	app := newApp(logger, grpcServer, registrar)
	return app, func() {
		cleanup()
	}, nil
}
