// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"lehu-video/app/base/service/internal/biz"
	"lehu-video/app/base/service/internal/conf"
	"lehu-video/app/base/service/internal/data"
	"lehu-video/app/base/service/internal/server"
	"lehu-video/app/base/service/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, registry *conf.Registry, confData *conf.Data, dataSetting *conf.DataSetting, logger log.Logger) (*kratos.App, func(), error) {
	db := data.NewDB(confData, logger)
	client := data.NewRedis(confData)
	dataData, cleanup, err := data.NewData(db, client, logger)
	if err != nil {
		return nil, nil, err
	}
	accountRepo := data.NewAccountRepo(dataData, logger)
	accountUsecase := biz.NewAccountUsecase(accountRepo, logger)
	accountServiceService := service.NewAccountServiceService(accountUsecase)
	authRepo := data.NewAuthRepo(dataData, logger)
	authUsecase := biz.NewAuthUsecase(authRepo, logger)
	authServiceService := service.NewAuthServiceService(authUsecase)
	fileRepo := data.NewBizFileRepo(dataData, logger)
	fileShardingConfig := data.NewFileShardingConfig(dataSetting)
	dataFileRepo := data.NewFileRepo(dataData, logger)
	fileRepoHelper := data.NewFileRepoHelper(fileShardingConfig, dataFileRepo)
	core := data.NewMinioCore(confData)
	minioRepo := data.NewMinioRepo(confData, core)
	fileUsecase := biz.NewFileUsecase(fileRepo, logger, fileRepoHelper, minioRepo)
	fileServiceService := service.NewFileServiceService(fileUsecase)
	grpcServer := server.NewGRPCServer(confServer, accountServiceService, authServiceService, fileServiceService, logger)
	httpServer := server.NewHTTPServer(confServer, accountServiceService, authServiceService, logger)
	registrar := server.NewRegistrar(registry)
	app := newApp(logger, grpcServer, httpServer, registrar)
	return app, func() {
		cleanup()
	}, nil
}
